### ISSUE TITLE
RemoteAccessCIDR Option

### ISSUE THREAD

**Issue by joshkurz** [aws-quickstart/quickstart-amazon-eks#10]
I see this option in the documentation, on this quick-start, however I was not aware it was possible to lock the master apis down for EKS. Is this a new option or did I miss something in the EKS docs? Could you share the link to the EKS docs where this option is available?

**Comment by joshkurz** [comment]
Also the linked PDF is where It talks about security for the K8s API.

```Security
Public access to Kubernetes API
We do not recommend enabling public access to the Kubernetes API. The IP range specified
in the RemoteAccessCIDR parameter is used to define which external address range has
access, and we recommend that you set this to allow access only from within the VPC
(10.0.0.0/16 by default) or to a trusted corporate CIDR block.```

I agree on not allowing public access to the API, however didn't think it was possible until I read that. So any clarification would be helpful. Thanks

**Comment by jaymccon** [comment]
Thanks for picking this up @joshkurz 

You're correct that this is not the case and appears due to a misprint in the guide. We've updated it removing the error.
