### ISSUE TITLE
EKS with Fargate integration

### ISSUE THREAD

**Issue by jeff1evesque** [aws-quickstart/quickstart-amazon-eks#103]
I'm trying to deploy my EKS cluster using [Fargate](https://docs.aws.amazon.com/eks/latest/userguide/fargate.html). Essentially my goals are to worry less about provisioning EC2 instances, used to deploy my cluster into. Rather, I'd like to configure Fargate, so that it can intelligently manage everything except my pod definitions. I'd like my EKS to interact with Fargate, and configured initially using cloudformation. Could anyone assist me find necessary information (hopefully examples) to boost my understanding, allowing me to do more with knowing less? I tried to search this entire repository for "fargate" and did not find anything. Also, youtube has several videos without any cloudformation solutions.

**Comment by jeff1evesque** [comment]
There are numerous examples of ECS integrated with Fargate:

- https://github.com/widdix/aws-cf-templates/blob/master/fargate/cluster.yaml
- https://github.com/nathanpeck/aws-cloudformation-fargate
- https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/ECS/FargateLaunchType/clusters/private-vpc.yml

But, I'd like to swap out ECS with EKS.

**Comment by jaymccon** [comment]
This can be done by specifying `FargateNamespaces` and `FargateLabels` parameters, which define the namespaces land labels to use to match pods for. Matching pods will be scheduled on Fargate. Worth noting that at present you still need a node group of at least 1 instance for kube-proxy and coredns to run on.

**Comment by jeff1evesque** [comment]
@jaymccon, can this now be done with CloudFormation?

**Comment by amitkatyal** [comment]
@jeff1evesque, I'm also planning to use EKS with Fargate. I understand that eksctl schedules core DNS on the Fargate but any idea of how to run it on the Fargate using CloudFormation?
