### ISSUE TITLE
Doesn't support cn-northwest-1 region

### ISSUE THREAD

**Issue by lobida** [aws-quickstart/quickstart-amazon-eks#106]
AWS China cn-northwest-1 region now has EKS. but currently it wasn't supported in the code.

**Comment by jaymccon** [comment]
both `cn-northwest-1` and `cn-north-1` are now supported. You will need to launch from our regional buckets, or build and copy to your own bucket in the region.

cn-northwest-1: https://aws-quickstart-cn-northwest-1.s3.cn-northwest-1.amazonaws.com.cn/quickstart-amazon-eks/templates/quickstart-amazon-eks-master.template.yaml

cn-north-1: https://aws-quickstart-cn-north-1.s3.cn-north-1.amazonaws.com.cn/quickstart-amazon-eks/templates/quickstart-amazon-eks-master.template.yaml

**Comment by elbertwang** [comment]
when I try to use this template in Cloudformation. it reported below msg.

S3 error: You are not authorized to perform this operation For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
