### ISSUE TITLE
error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by schlichtanders** [aws-quickstart/quickstart-amazon-eks#109]
When trying to run the quickstart-amazon-eks I get the following error
```
EksNodeUser Custom::KubeManifest CREATE_FAILED Failed to create resource. error: You must be logged in to the server (Unauthorized)
```
which seems to indicate, that kube authentification is not properly setup, however the EksNodeUser is the very first component for user authentification, created before all other user-authentifications (if I understood it right)

**Comment by schlichtanders** [comment]
I debugged further and my best guess so far is that the reason behind is following:
* I split up the large template into multiple parts, deploying them with separate boto3 sessions
* each boto3 session gets its own caller arn
* when creating the EKS, the only arn which is authorized is the one creating it. Hence another boto3 session nolonger has permissions

not tested yet, soon to come

**Comment by schlichtanders** [comment]
I fixed the session name so that now every session has exactly the same name, but I still get the above error.

@jaymccon can you help me here, how have you enabled your KubeManifest custom lambda cloudformation to actually access the EKS?

The issue I constantly face is that only the very same user-arn which created the EKS can also change things on it, but the lambda authentifies with a different role-arn.

**Comment by jaymccon** [comment]
This is done by the [CfnAssumeRole custom resource](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/functions/source/CfnStackAssumeRole/lambda_function.py) which launches the control plane stack using the `ControlPlaneProvisionRole`
