### ISSUE TITLE
Why are there two different NodeInstanceRole?

### ISSUE THREAD

**Issue by schlichtanders** [aws-quickstart/quickstart-amazon-eks#110]
I just wanted to adapt the template to support SSM instead of ssh keypair. This is when I stumbled upon that there are currently two IAM::Role name `NodeInstanceRole`, so my question is which of these to adapt if I want to adapt for SSM?

The one is in the iam.template https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks-iam.template.yaml#L236-L269

The other in the nodegroup.template itself https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks-nodegroup.template.yaml#L728-L744

Both are apparently used within the nodegroup.template (the former via the input parameter `NodeInstanceRoleName`)

**Comment by schlichtanders** [comment]
It seems like a related question is what is the difference between the `NodeGroup` resource and the `EKSNodeGroup` resource?

**Comment by troy-ameigh** [comment]
The Difference between the NodeGroup and the EKSNodeGroup, is the following. The NodeGroup stansa defines a need group that can be used with or without the QS autoscaler. The EKSNodeGroup defines the new Managed Node Group feature that is in EKS 1.14 and higher. (See https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html for more detail.
