### ISSUE TITLE
Deploying via my own S3 bucket fails CopyZip resource

### ISSUE THREAD

**Issue by clayvan** [aws-quickstart/quickstart-amazon-eks#111]
So I might be doing something completely wrong here, but I have a hunch that what is currently in the S3 bucket, and what is in this repo does not match.

If I deploy a cloudformation stack using the URL in the getting started guide, I get a successful Stack Creation: https://s3.amazonaws.com/aws-quickstart/quickstart-amazon-eks/templates/amazon-eks-master.template.yaml

If I clone this repo, upload it to S3, and use that URL, my Stack fails to create. I've made this bucket public.
https://clayvan-eks-iac.s3.us-east-2.amazonaws.com/quickstart-amazon-eks/templates/amazon-eks-master.template.yaml

The failure is during the Functions Stack and the CopyZip resource.
```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
```

I don't see any obvious changes made in the IAM or Functions templates that would have broken this.

I've tried downloading the S3 bucket and comparing it to this git repo and I don't see any differences in the templates.

So my questions are:
1. What is different about using the AWS quick start S3 bucket and using my own bucket with the same code in it?
2. If the code is the exact same, why am I failing this CopyObject operation when using my own bucket?

Also, it looks like this was already brought up as an issue by another user, who then closed the issue right away without a solution 😄: https://github.com/aws-quickstart/quickstart-amazon-eks/issues/99

**Comment by schottsfired** [comment]
Refer to https://github.com/aws-quickstart/quickstart-amazon-eks/issues/99#issuecomment-604121086
