### ISSUE TITLE
Parameter RemoteAccessCIDR failed to satisfy constraint: CIDR block parameter must be in the form x.x.x.x/x

### ISSUE THREAD

**Issue by KOSSOKO** [aws-quickstart/quickstart-amazon-eks#113]
I'm new on eks
I'm deploying the quick start using the template but at the last step, I got this error:

> Parameter RemoteAccessCIDR failed to satisfy constraint: CIDR block parameter must be in the form x.x.x.x/x

I could I correct it in order to deploy it ?
A last question, what is the difference between this official deployment tutorial : https://docs.aws.amazon.com/eks/latest/userguide/getting-started-console.html

and this one you provide https://aws.amazon.com/fr/quickstart/architecture/amazon-eks/
?
Thanks in advance.

**Comment by troy-ameigh** [comment]
KOSSOKO,

When you call the QuickStart in CloudFormation there is a field for the "RemoteAccessCIDR" paramater. You need to put in the IP CIDR block you your system is on so you can access the bastion. You maybe you corporate CIDR block so multiple people can access the bastion host. You can add 0.0.0.0/0 however we dont recommend leaving it this way as it will allow anyone from anywhere to access the bastion host for your environment. Once the environment is built your can modify this in the "BastionSecurityGroup" that gets created in your environment. 

As for the difference in the QuickStart deployment guide and the general EKS getting started documentation. The QuickStart start follows all AWS best practices, however it does give you some choices in how you wish to deploy an EKS stack that is a production ready environment.  Using the QuickStart, you can deploy production ready EKS environments in the same repetitive manner time after time. 

If you read the following blog you can see how you can use AWS CloudFormation and Helm to deploy Helm charts into you EKS cluster once you have deployed it with the QuickStart. 

[Using AWS CloudFormation to deploy software into Amazon EKS clusters](https://aws.amazon.com/blogs/infrastructure-and-automation/using-aws-cloudformation-to-deploy-software-into-amazon-eks-clusters/)

**Comment by KOSSOKO** [comment]
@troy-ameigh thanks a lot for this very well explanation. Thank you.

**Comment by KOSSOKO** [comment]
@troy-ameigh thanks a lot for this very well explanation. Thank you.

**Comment by KOSSOKO** [comment]
@troy-ameigh after correcting the RemoteAccesCIDR, I got this error: 

> Requires capabilities : [CAPABILITY_IAM]
without more information. How could I correct it ?
Thanks in advance.
[https://www.noelshack.com/2020-14-1-1585581509-annotation-2020-03-30-171743.jpeg
](url)

**Comment by KOSSOKO** [comment]
Now I have this error that comes each time i replay the stack
![Annotation 2020-03-30 180417](https://user-images.githubusercontent.com/11942543/77944172-c0125100-72be-11ea-9d98-aad98c44c7c3.jpeg)

**Comment by KOSSOKO** [comment]
ok, this is due to vpc ip limitation. The number of new ip allocated by aws is 5. We need to send information to aws and ask them to increase to 10.
