### ISSUE TITLE
EFS  Support with managed node pool

### ISSUE THREAD

**Issue by sukrit007** [aws-quickstart/quickstart-amazon-eks#114]
It seems that managed node pool provisioning can not be used with EFS as the security group used by EFS stack is created by managed node pool and it is different from what is created in the stack. 

We might have to write a custom resource to fetch the value of the auto-created security group (by filtering by tag:  aws:eks:cluster-name = <cluster-name> and passing this security group to  https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks-efs.template.yaml.  

I will possibly work on submitting a PR for the same.

**Comment by navbalaraman** [comment]
I am facing the same issue now. When i turn on EfsStorageClass with Managed Node groups it fails to deploy the efsprovisioner. Is there a fix coming soon?

**Comment by troy-ameigh** [comment]
This was added in Commit 89e2fd65826c284828053cb0d1d07f7f655815bf
