### ISSUE TITLE
Race Condition - IAM Stack Not Created Before NodeGroupStack

### ISSUE THREAD

**Issue by judahb** [aws-quickstart/quickstart-amazon-eks#116]
Error message

Parameters: [NodeInstanceRoleArn] must have values

**Comment by troy-ameigh** [comment]
We are reviewing this. However with the "!GetAtt IamStack.Outputs.NodeInstanceRoleName" in the template the NodeGroupStack is already dependent on the IAMStack. Do you have any errors or logs you can share. Thanks

**Comment by schottsfired** [comment]
I hit the same thing a few days ago and fixed it with https://github.com/aws-quickstart/quickstart-cloudbees-core/pull/24. The `nodegroup.template` has a new required parameter, so just need to make sure you pass it in when you create a nodegroup.

I have no idea if there's a race condition somewhere, but I know you can get the `NodeInstanceRoleArn` from the outputs of `amazon-eks.template.yaml`.

**Comment by troy-ameigh** [comment]
The amazon-eks.template.yaml passes the "NodeInstanceRoleArn" to the amazon-eks-nodegroup.template.yaml. I am testing a minor change that may help.
