### ISSUE TITLE
Customize EKS Cluster Name

### ISSUE THREAD

**Issue by MihaiSprinceana** [aws-quickstart/quickstart-amazon-eks#118]
Add additional field: "EKS Cluster name" to the existing templates.

**Comment by KOSSOKO** [comment]
Did you find a solution ? I want also to customize the cluster name in order to have the same cluster name when I redploy my cloudformation template.

**Comment by jaymccon** [comment]
What benefit does being able to re-deploy with the same name provide ? I typically leave name fields out of CloudFormation templates, because naming resources blocks updates to fields that require replacement.

**Comment by KOSSOKO** [comment]
@jaymccon I have a gitlab cicd config file that connects to the cluster using awscli command. The connection is done throught the name of the cluster. I have multiple config file. It is a pain, each time i deploy the cloudformation template to update all cluster name in the config file.

**Comment by jaymccon** [comment]
If you know the CloudFormation stack name you can fetch the cluster name and setup kubeconfig with something like:

```bash
CFN_STACK_NAME=MyEksStack
EKS_CLUSTER_NAME=$(aws cloudformation describe-stacks --stack-name ${CFN_STACK_NAME} --query 'Stacks[0].Outputs[?OutputKey==`EKSClusterName`].OutputValue' --output text)
aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME}
```

**Comment by KOSSOKO** [comment]
You are a master. Thanks a lot. Thank you.

**Comment by KOSSOKO** [comment]
it works perfectly.

**Comment by tomiszili** [comment]
With the EKS cluster name parameter stage (e.g.: dev, test, pre-prod, prod) separation would be easier.

**Comment by jaymccon** [comment]
Because of the limitations on CloudFormation stack updates and rollback that allowing setting an explicit cluster name introduces it's unlikely we'll implement this. For defining stages it is recommended to use stack tags, which requires https://github.com/aws-quickstart/quickstart-amazon-eks-cluster-resource-provider/issues/2 to be implemented before the'll propagate to the eks cluster.

**Comment by tlindsay42** [comment]
Launched in https://github.com/aws-quickstart/quickstart-amazon-eks/commit/87869788e4fa04e872c5d4e1e306c4b45315e7c8
