### ISSUE TITLE
Document lambda functions better

### ISSUE THREAD

**Issue by ngarg1234** [aws-quickstart/quickstart-amazon-eks#119]
What is the need of deploying Lambda functions. I am new to EKS, so i am confused because of this. If you can explain me the purpose of writing template (amazon-eks-functions.template.yaml). It would be great. Thanks!

**Comment by jaymccon** [comment]
The lambda functions are used to extend what is functionality is available natively in CloudFormation, such as deploying kubernetes manifests, cleaning up loadbalancers and ebs volumes that are created by kubernetes load balancers and PVC's.

**Comment by kbhat** [comment]
@jaymccon Even I am having the same question. If you can walk us through an example, it would be great.

Let's say I used this quickstart guide to deploy EKS cluster (with nodes) in new VPC. When exactly are these lambda functions getting called during this scenario and for what purpose?

If I were to take "CleanupLoadBalancersLambda" as an example, do you mean that the loadbalancer created by Kubernetes is deleted by cloudformation every time we call cloudformation script? Appreciate if you can clear this doubt. 

Thanks in advance!

**Comment by jaymccon** [comment]
Lambdas who's function is to cleanup aws resources created by kubernetes are no-ops for stack create and update.

**Comment by jaymccon** [comment]
closing in favor of #104
