### ISSUE TITLE
Cloudformation location - s3 vs github

### ISSUE THREAD

**Issue by yanivpaz** [aws-quickstart/quickstart-amazon-eks#121]
Hi
I am looking for github location of cloudformation templates which are located in s3 bucket 

for example :
aws s3 ls s3://amazon-eks/cloudformation/2019-02-11

**Comment by jaymccon** [comment]
This project is the source for the [EKS Quick Start](https://aws.amazon.com/quickstart/architecture/amazon-eks/) refeerence architecture, and is not the source for the `amazon-eks` bucket.
