### ISSUE TITLE
How can we achieve Multi Region Worker nodes for EKS cluster?

### ISSUE THREAD

**Issue by SrinivReddy** [aws-quickstart/quickstart-amazon-eks#122]
We have a EKS cluster on us-east-1 and we want to add a worker node to cluster which is part of us-west-2. IS it possible, how can we achieve this, any solution you have for this?

**Comment by jaymccon** [comment]
It is unlikely that the Quick Start will ever solve this. CloudFormation Stacks are by design region constrained, and as far as I'm aware there is no broadly accepted solution for spanning a single cluster across multiple locations.
