### ISSUE TITLE
Received 0 SUCCESS signal(s) out of 3 NodeGroupStack

### ISSUE THREAD

**Issue by FelipeMiranda** [aws-quickstart/quickstart-amazon-eks#124]
Steps:

1 - aws s3 cp --recursive s3://aws-quickstart/quickstart-amazon-eks/ ./quickstart-amazon-eks/
as @jaymccon suggested here #123 uploaded to a custom s3 bucket, but I get theses erros:

```
| CREATE_FAILED | The following resource(s) failed to create: [NodeGroup].
| NodeGroup | CREATE_FAILED | Received 0 SUCCESS signal(s) out of 3. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
NodeGroup | UPDATE_IN_PROGRESS | Failed to receive 3 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.

```

I'm working on master branch.

**Comment by jaymccon** [comment]
you'll need to get to the logs on the instances to determine cause of timeout failures. Commonly it's networking issues preventing the instances from communicating with CloudFormation. First log to look at would be `/var/log/cloud-init-cmd.log`

**Comment by jaymccon** [comment]
closing as stale
