### ISSUE TITLE
FunctionStack/RegisterType creation failed

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#127]
Hi!

I Copied the repo into my account and I started the CF deployment with `amazon-eks-master.template.yaml`, but it failed in the FunctionStack section.
The error I got is the following:
<img width="883" alt="2020-04-21_17h35_19" src="https://user-images.githubusercontent.com/54439475/79887003-4facaa80-83fa-11ea-83fe-16f6105aeebd.png">

And the Lambda error log event is:
```
{
    "timestamp": "2020-04-21 15:49:48,393",
    "level": "ERROR",
    "location": "crhelper.resource_helper._wrap_function:193",
    "RequestType": "Create",
    "StackId": "arn:aws:cloudformation:eu-central-1:471509798482:stack/eks5-EKSStack-1RYKZR2PG5QQV-FunctionStack-1VBFLQYBLIIK5/91405d60-83e7-11ea-a65d-0a3f04c080ce",
    "RequestId": "0fdc7d8a-f400-4207-b08b-2aadc1f96f4b",
    "LogicalResourceId": "RegisterType",
    "aws_request_id": "60c3f462-accf-48bf-b31b-4b26077c9214",
    "message": "Failed to register resource {'ProgressStatus': 'FAILED', 'Description': \"Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\\nDeployment failed with exception: com.amazonaws.providerruntime.utils.exceptions.ValidationException with error msg : [f0ec3b77-fd36-45aa-b312-e66d01f1a2b5] Invalid 'protocolVersion' settings in .rpdk-config.\", 'ResponseMetadata': {'RequestId': 'bb0b0bba-cc9d-4baf-9d72-4d2e441a45dc', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'bb0b0bba-cc9d-4baf-9d72-4d2e441a45dc', 'content-type': 'text/xml', 'content-length': '698', 'date': 'Tue, 21 Apr 2020 15:49:47 GMT'}, 'RetryAttempts': 0}}",
    "exception": "Traceback (most recent call last):\n  File \"/opt/python/crhelper/resource_helper.py\", line 191, in _wrap_function\n    self.PhysicalResourceId = func(self._event, self._context) if func else ''\n  File \"/var/task/lambda_function.py\", line 39, in register\n    version_arn = stabilize(response['RegistrationToken'], cfn)\n  File \"/var/task/lambda_function.py\", line 19, in stabilize\n    raise Exception(f\"Failed to register resource {p}\")\nException: Failed to register resource {'ProgressStatus': 'FAILED', 'Description': \"Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\\nDeployment failed with exception: com.amazonaws.providerruntime.utils.exceptions.ValidationException with error msg : [f0ec3b77-fd36-45aa-b312-e66d01f1a2b5] Invalid 'protocolVersion' settings in .rpdk-config.\", 'ResponseMetadata': {'RequestId': 'bb0b0bba-cc9d-4baf-9d72-4d2e441a45dc', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'bb0b0bba-cc9d-4baf-9d72-4d2e441a45dc', 'content-type': 'text/xml', 'content-length': '698', 'date': 'Tue, 21 Apr 2020 15:49:47 GMT'}, 'RetryAttempts': 0}}"
}
```

What should i do differently?

**Comment by cwardcode** [comment]
I'm having the same issue, regardless of the various options I've tried, I cannot get the stack to create, nor can I get a previous version of the quickstart to run 😢

**Comment by indra0007** [comment]
I am getting the same issue. Looks like it's broken. Kindly help

**Comment by indra0007** [comment]
eksctl is a better option in this scenario to create a EKS cluster

**Comment by cwardcode** [comment]
@jaymccon It looks like it was broken with this commit 11 days ago https://github.com/aws-quickstart/quickstart-amazon-eks/commit/0bf72f132fbe9c34c84e4d2b9b2e0a603ec06d0b due to switching away from the custom provider. Unfortunately I'm not familiar enough with CDK to spot the actual issue. Any help is appreciated!

**Comment by techcto** [comment]
It was working yesterday, something must have happened.

**Comment by jaymccon** [comment]
upstream change has caused this, fix incoming

**Comment by jaymccon** [comment]
can confirm this is fixed by ea47e15 . Cause was a change in the CloudFormation service that affected the CloudFormation cli go plugin https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/pull/140

**Comment by techcto** [comment]
> eksctl is a better option in this scenario to create a EKS cluster

Can you describe the various scenarios where one might use the Quickstart and Cloudformation vs. eksctl. I have used both and personally just feel comfortable with Cloudformation for the audit trail.

**Comment by schottsfired** [comment]
I saw the bat-signal and arrived as soon as I could. Hope I didn't miss anything.

**Comment by jaymccon** [comment]
quickstart-cloudbees-core should be unaffected by this as the submodule is prior to the switch to a custom type for EKS::Cluster
