### ISSUE TITLE
TaskCat test failing with "Invalid or unsupported Type AWSQS::EKS::Cluster"

### ISSUE THREAD

**Issue by zhangwenjia0326** [aws-quickstart/quickstart-amazon-eks#129]
As part of this PR: https://github.com/aws-quickstart/quickstart-amazon-eks/commit/0bf72f132fbe9c34c84e4d2b9b2e0a603ec06d0b#diff-514fc2d5697d617906bd258ad0af2e30 the control plane deployment started using a registered private resource type AWSQS::EKS::Cluster

This change is working fine for me during a normal deployment, however if I run a TaskCat test against this definition, it fails right away with the below error:
"[0m :     line 86 [3001] [Basic CloudFormation Resource Check] Invalid or unsupported Type AWSQS::EKS::Cluster for resource EKS in us-east-2"
It seems like TaskCat do not consider any private resource type when doing resource check. 

Please kindly advise on how we should run TaskCat test with these new changes.

**Comment by jaymccon** [comment]
Is this still the case with the latest master branch? 

The private resource should be automatically packaged by taskcat from the `functions/source/EksClusterResource` path. Then [RegisterEksClusterType](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks-functions.template.yaml#L177-L186) in the functions stack should register the type into the target account.

**Comment by schottsfired** [comment]
I think this is about the lint errors when deploying EKS QS with `taskcat`. I hit the same thing today and was wondering if cfn-lint has any knowledge of EKS QS custom resources like `AWSQS::EKS::Cluster`? Seems like it's missing.

Workaround is to use `taskcat test run -l` (dash L) to disable linting.

**Comment by jaymccon** [comment]
latest version of taskcat+cfn-lint is able to read the `.cfnlintrc` file containing pointers to the added resource types. #162 introduces cfn-lint compliant templates, so should be able to keep linting on once that is merged.
