### ISSUE TITLE
EFS Storage Class

### ISSUE THREAD

**Issue by maguire007** [aws-quickstart/quickstart-amazon-eks#13]
It would be kinda awesome if the quickstart had an option to create a EFS filesystem.  It would update the EKS worker SG for NFS, and the target SG for NFS, and deploy the EFS efs-provisioner helm chart with the filesystemid. We be nice having a cluster started up with EFS storage class waiting to be used.

**Comment by jaymccon** [comment]
Enabling EFS out of the box is definitely something we aim to do, either via efs-provisioner or https://github.com/aws/containers-roadmap/issues/147

**Comment by jaymccon** [comment]
implemented in 2aef27fe69df6c15bb57eb2ca1de86bcd7833a1e
