### ISSUE TITLE
RegisterType keeps failing

### ISSUE THREAD

**Issue by techcto** [aws-quickstart/quickstart-amazon-eks#130]
I just tested the base eks quickstart and unless I have something cached, what worked yesterday has been failing today.  It seems to revolve around the RegisterType function.

Here are the logs from Lambda (cleaned):

{
    "timestamp": "2020-04-22 18:35:16,640",
    "level": "DEBUG",
    "location": "crhelper.resource_helper.__call__:72",
    "RequestType": "Create",
    "LogicalResourceId": "RegisterType",
    "message": {
        "RequestType": "Create",
        "ServiceToken": "arn:aws:lambda:us-east-1:*:function:eks-123-RegisterTypeFunction-12NOYH7TFST74",
        "StackId": "arn:aws:cloudformation:us-east-1:*:stack/eks-123-FunctionStack-1P3Q3F31ZQ43V/dd229190-84c7-11ea-be9f-12505ef78976",
        "RequestId": "*",
        "LogicalResourceId": "RegisterType",
        "ResourceType": "Custom::RegisterType",
        "ResourceProperties": {
            "ServiceToken": "arn:aws:lambda:us-east-1:*:function:eks-123-RegisterTypeFunction-12NOYH7TFST74",
            "ExecutionRoleArn": "arn:aws:iam::***:role/eks-123-HATX28J-ExecutionRole-Y9G5U09ZT05E",
            "TypeName": "AWSQS::EKS::Cluster",
            "LogGroupName": "awsqs-eks-cluster-logs",
            "SchemaHandlerPackage": "s3://eks-123/quickstart-amazon-eks/functions/packages/EksClusterResource/awsqs-eks-cluster.zip",
            "LogRoleArn": "arn:aws:iam::*:role/eks-123-LogDeliveryRole-1M591XEZSUK00"
        }
    }
}

{
    "timestamp": "2020-04-22 18:35:16,652",
    "level": "ERROR",
    "location": "lambda_function.register:27",
    "RequestType": "Create",
    "LogicalResourceId": "RegisterType",
    "message": "event: {\"RequestType\": \"Create\", \"ServiceToken\": \"arn:aws:lambda:us-east-1:*:function:eks-123-RegisterTypeFunction-12NOYH7TFST74\", \"ResponseURL\": \"https://cloudformation-custom-resource-response-useast1.s3.amazonaws.com/arn%3Aaws%3Acloudformation%3Aus-east-1%3A*%3Astack/eks-123HATX28JM-FunctionStack-1P3Q3F31ZQ43V/dd229190-84c7-11ea-be9f-12505ef78976%7CRegisterType%7C73c6d85d-b8ca-42d3-93ab-7312bb85e755?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200422T183515Z\", \"StackId\": \"arn:aws:cloudformation:us-east-1:*:stack/eks-123HATX28JM-FunctionStack-1P3Q3F31ZQ43V/dd229190-84c7-11ea-be9f-12505ef78976\", \"RequestId\": \"73c6d85d-b8ca-42d3-93ab-7312bb85e755\", \"LogicalResourceId\": \"RegisterType\", \"ResourceType\": \"Custom::RegisterType\", \"ResourceProperties\": {\"ServiceToken\": \"arn:aws:lambda:us-east-1:*:function:eks-123-RegisterTypeFunction-12NOYH7TFST74\", \"ExecutionRoleArn\": \"arn:aws:iam::*:role/eks-123HATX28J-ExecutionRole-Y9G5U09ZT05E\", \"TypeName\": \"AWSQS::EKS::Cluster\", \"LogGroupName\": \"awsqs-eks-cluster-logs\", \"SchemaHandlerPackage\": \"s3://eks-tmp-221830-eksstack-18h89hat-lambdazipsbucket-1lajvfgc32y2q/quickstart-amazon-eks/functions/packages/EksClusterResource/awsqs-eks-cluster.zip\", \"LogRoleArn\": \"arn:aws:iam::*:role/eks-123HATX2-LogDeliveryRole-1M591XEZSUK00\"}}"
}

{
    "timestamp": "2020-04-22 18:35:32,213",
    "level": "ERROR",
    "location": "crhelper.resource_helper._wrap_function:193",
    "RequestType": "Create",
    "StackId": "arn:aws:cloudformation:us-east-1:*:stack/eks-123HATX28JM-FunctionStack-1P3Q3F31ZQ43V/dd229190-84c7-11ea-be9f-12505ef78976",
    "RequestId": "73c6d85d-b8ca-42d3-93ab-7312bb85e755",
    "LogicalResourceId": "RegisterType",
    "aws_request_id": "ff8f74b5-f1e1-4d09-881c-dc905b751ab6",
    "message": "Failed to register resource {'ProgressStatus': 'FAILED', 'Description': \"Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\\nDeployment failed with exception: com.amazonaws.providerruntime.utils.exceptions.ValidationException with error msg : [1ef186c7-2ccc-4d76-b914-8c7f795daf98] Invalid 'protocolVersion' settings in .rpdk-config.\", 'ResponseMetadata': {'RequestId': '85b18d30-7c4a-4acc-8105-dbfc92b6cc00', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '85b18d30-7c4a-4acc-8105-dbfc92b6cc00', 'content-type': 'text/xml', 'content-length': '698', 'date': 'Wed, 22 Apr 2020 18:35:32 GMT'}, 'RetryAttempts': 0}}",
    "exception": "Traceback (most recent call last):\n  File \"/opt/python/crhelper/resource_helper.py\", line 191, in _wrap_function\n    self.PhysicalResourceId = func(self._event, self._context) if func else ''\n  File \"/var/task/lambda_function.py\", line 39, in register\n    version_arn = stabilize(response['RegistrationToken'], cfn)\n  File \"/var/task/lambda_function.py\", line 19, in stabilize\n    raise Exception(f\"Failed to register resource {p}\")\nException: Failed to register resource {'ProgressStatus': 'FAILED', 'Description': \"Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\\nDeployment failed with exception: com.amazonaws.providerruntime.utils.exceptions.ValidationException with error msg : [1ef186c7-2ccc-4d76-b914-8c7f795daf98] Invalid 'protocolVersion' settings in .rpdk-config.\", 'ResponseMetadata': {'RequestId': '85b18d30-7c4a-4acc-8105-dbfc92b6cc00', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '85b18d30-7c4a-4acc-8105-dbfc92b6cc00', 'content-type': 'text/xml', 'content-length': '698', 'date': 'Wed, 22 Apr 2020 18:35:32 GMT'}, 'RetryAttempts': 0}}"
}

I have done numerous tests, so I wonder if it is related to the ServiceToken or some other type of service limit?

**Comment by cwardcode** [comment]
Duplicate of #127

**Comment by techcto** [comment]
Agree.  I will move there. Thank you!
