### ISSUE TITLE
support helm3?

### ISSUE THREAD

**Issue by Forest-L** [aws-quickstart/quickstart-amazon-eks#134]
Hi, The helm version is 2.16.3 on EKS, whether support helm3 or not?

**Comment by ThisIsQasim** [comment]
Same. Would very much appreciate if the bastion came with helm 3 pre-installed

**Comment by bnusunny** [comment]
+1

**Comment by calvinyv** [comment]
+1

**Comment by pixiake** [comment]
+1

**Comment by yunkunrao** [comment]
+1

**Comment by troy-ameigh** [comment]
We are currently looking into this.

**Comment by jaymccon** [comment]
this was delivered in 9a16037dd11a1eb2f94467ac790b8334972da2bd 3120adaabbf99db6110f643d435030b5117e46b4 and de5752e8ba5847418b0769352d54412ca0f4d6d5
