### ISSUE TITLE
Enabling Managed NodeGroup causes intermittent stack failure during nodegroup stack installation

### ISSUE THREAD

**Issue by navbalaraman** [aws-quickstart/quickstart-amazon-eks#135]
I tried deploying this in multiple regions. It succeeds mostly but sometimes it fails with the error below. Need your expert help on this. We are trying to reuse this for a customer.

[April 28, 2020, 3:04 PM] : 2020-04-28 14:35:54 UTC-0500	EKSNodegroup	CREATE_FAILED	Nodegroup EKSNodegroup-UbDwwj5vrs4j failed to stabilize: Internal Failure
[April 28, 2020, 3:04 PM] : aws-eks-cluster2020-04-28T18-48-44-EKSStack-C3IBSNBDG5YE-NodeGroupStack-1EHK28PAFLKDD
NESTED

**Comment by troy-ameigh** [comment]
navbalaraman:

What Regions are you seeing this failure in.

**Comment by navbalaraman** [comment]
It failed on us-east-1 and us-east-2. On subsequent attempt it passed as well. Seems intermittent.

**Comment by troy-ameigh** [comment]
navbalaraman, after review this does not appear to be an issue with the QS. But more of a possible issue with the service.

**Comment by navbalaraman** [comment]
Thanks a lot Troy.
