### ISSUE TITLE
Cloudfromation Stack error

### ISSUE THREAD

**Issue by lukacsbarnabas78** [aws-quickstart/quickstart-amazon-eks#14]
I've tried to deploy an EKS environment into a new VPC using https://s3.amazonaws.com/aws-quickstart/quickstart-amazon-eks/templates/amazon-eks-master.template.yaml template with default settings.
I got the following error:
The following resource(s) failed to create: [BastionStack, NodeGroupStack]. 

Is there a bug in CF template? Can anyone help me with deploying the environment?

Thank you in advance

**Comment by virtlima** [comment]
Are you modifying any of the QSS3BucketName Parameters? The NodeGroupStack is failing because the BastionStack failed to created, can you provide the error that is under events for the BastionStack?

**Comment by CoravinOpenCart** [comment]
I found it the issue in ASG (This account is currently blocked and not recognized as a valid account. Please contact aws-verification@amazon.com if you have questions.) I created the EKS in a new account and AWS blocked my account.

**Comment by ishaannarang** [comment]
i am facint the same issue. not modifying the QSS3BucketName

**Comment by ishaannarang** [comment]
the issue is resolved as my account did not have free eips

**Comment by bcornw2** [comment]
I am currently facing this same issue. How many elastic IPs do I need? What else could be causing it? I am leaving all S3 stuff as default, the only values I am changing are stack name, cluster name, and remoteAccessCIDR range.

**Comment by bcornw2** [comment]
>Embedded stack arn:aws:cloudformation:us-east-2:X0X0X0X0X0X0:stack/CFI-Prisma-Cloud-DDC-EKSStack-1XXXXXXXTN6VN/f5exxxxx-2xxe-11xd-8d5e-0xxxxx8cd4 was not successfully created: The following resource(s) failed to create: [BastionStack, NodeGroupStack].

**Comment by bcornw2** [comment]
![image](https://user-images.githubusercontent.com/33430452/186939564-6cb2798e-dc1c-477b-84d3-20d90c245051.png)
