### ISSUE TITLE
Cloudformation YAMLException

### ISSUE THREAD

**Issue by aleksandarnasuovski** [aws-quickstart/quickstart-amazon-eks#142]
Noticed yaml exception while deploying EKS into a new VPC. 

 5/13/2020, 12:34:01 PM - Cannot render the template because of an error.: YAMLException: unknown tag !<!Contains> at line 430, column 3: ClusterAutoScalerVerification: ^

File was fetched from URL: https://s3.amazonaws.com/aws-quickstart/quickstart-amazon-eks/templates/amazon-eks-master.template.yaml

**Comment by jaymccon** [comment]
Looks like whatever you're using to parse the template doesn't understand `!Contains` which is valid, but only documented in the [Service Catalog docs](https://docs.aws.amazon.com/servicecatalog/latest/adminguide/reference-template_constraint_rules.html).
