### ISSUE TITLE
Failed to create resource. [Errno 2] No such file or directory: 'helm': 'helm'

### ISSUE THREAD

**Issue by techcto** [aws-quickstart/quickstart-amazon-eks#143]
Failed to create resource. [Errno 2] No such file or directory: 'helm': 'helm'

I just started getting this error yesterday after I had everything working.  I think the EKSClusterResource slipped in an update, but it still did not work after reverting. Maybe cache?  Any idea how this error would just pop up?

This is in the Helm Lambda.

**Comment by jaymccon** [comment]
Are you using the `aws-quickstart` bucket or do you have your own bucket ?

**Comment by jaymccon** [comment]
closing this as stale
