### ISSUE TITLE
Bug report - QuickStart Amazon EKS

### ISSUE THREAD

**Issue by mantshongoS** [aws-quickstart/quickstart-amazon-eks#148]
I created an EKS cluster using the CloudFormation(CFN) QuickStart template below[1]. 

Observations
--------------
1. If I set the EfsThroughputMode to "Burst" with Prometheus and Grafana the CloudFormation (CFN) Stack will complete successfully. 

2. However, if I set the EfsThroughputMode  to "Provisioned" with Prometheus&Grafana the Stacks Fails to create. 

I have tried creating the CFN Stack multiple times in different regions and I observed the same behavior. 

[1] https://github.com/aws-quickstart/quickstart-cloudbees-core

**Comment by troy-ameigh** [comment]
Thank you for bring this to our attention. We are looking into this.
