### ISSUE TITLE
Enhance the HelmLambda to accept a release name and chart version

### ISSUE THREAD

**Issue by gavincornwell** [aws-quickstart/quickstart-amazon-eks#15]
The HelmLambda custom resource doesn't currently allow a release name to be provided or for a version of the chart to be provided.

This is something we need for our use case, we plan to implement this in a fork and will submit as a pull request as soon as we can.

**Comment by jaymccon** [comment]
chart version can be specified with `Version` property (will add it to the example template). Working on adding name

**Comment by gavincornwell** [comment]
Thanks for adding this so quickly.
