### ISSUE TITLE
Request: Provision multiple nodegroups (Managed/Unmanaged)

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#150]
The cluster and nodegroup templates should be separated and the nodegroups should be deployed as a second step. In case of someone wants to provision multiple nodegroups (managed/unmanaged).

I think one logical unit is the vpc, eks (empty cluster), functions, iam and the bastion host, and the other logical unit is the nodegroup (managed/unmanaged), and the last logical unit is the example workload.

What do you think about this idea?

**Comment by jaymccon** [comment]
I agree that nodegroup should be seen as 1-many in their relationship with clusters, although I'm not sure we'd want to force an extra step on users. As it stands today the nodegroup template can be launched standalone to add extra nodegroups, and this is the pattern we will follow for any additional nodegroup templates that get added down the line.

**Comment by gargana** [comment]
https://github.com/aws-quickstart/quickstart-amazon-eks-nodegroup/

The CloudFormation templates can also be launched from the aws-quickstart buckets.

s3://aws-quickstart/quickstart-amazon-eks/submodules/quickstart-amazon-eks-nodegroup/templates/amazon-eks-nodegroup.template.yaml
