### ISSUE TITLE
Nodegroup instances are unencrypted

### ISSUE THREAD

**Issue by yannickvr** [aws-quickstart/quickstart-amazon-eks#151]
Nodegroup template does not support EBS encryption. Seems like best practise to add this functionality.

**Comment by NunoDSFernandes** [comment]
Hi,

I found this issue, and it does support EBS encryption:

Activate encryption as default on the EBS settings, and set that to the default key.
If you do that, you can set the template to encrypt the EBS volumes.

However, if any key except the default encryption is set on the EBS settings or on the template, the deployment will fail.
