### ISSUE TITLE
Support 1.17

### ISSUE THREAD

**Issue by clayvan** [aws-quickstart/quickstart-amazon-eks#158]

**Comment by kn0xyland** [comment]
Keen for this as well, any ETA?

**Comment by troy-ameigh** [comment]
This is being added to the next release of the Quick Start which is V.3. We are working on a hard release date, but should be in the near future.

**Comment by kn0xyland** [comment]
<3 AWS Cloudformation. Thank you for the prompt reply! Keep well everyone

**Comment by rushabh268** [comment]
Is this done? Is there an ETA on this?

**Comment by jaymccon** [comment]
implemented in #162
