### ISSUE TITLE
Internal Failure - EKS Stack - MapPublicIpOnLaunch for Subnets

### ISSUE THREAD

**Issue by carloarteaga1** [aws-quickstart/quickstart-amazon-eks#159]
The quickstart is failing completely for me and others on the internet.

Error recieved is "Internal Failure" when the EKSControlPlane attempts to be created.

Searching online seems to point to the April 22 change to Subnet "MapPublicIpOnLaunch" versus the old setting.  Information on change documented here: https://aws.amazon.com/blogs/containers/upcoming-changes-to-ip-assignment-for-eks-managed-node-groups/

I believe the fix would in the VPC quickstart project code but I'm no expert with Cloudformation I lean on you to verify the case: https://github.com/aws-quickstart/quickstart-aws-vpc
 
Please double check my claims for more concrete root cause analysis and solution.  I hop this fix can be made quickly and easily so I can continue working with EKS and microservices in the AWS cloud.  Thanks! :)

**Comment by jaymccon** [comment]
I'm tempted to close this as stale. We've not picked this up in our testing, probably because the VPC we create has nodes in private subnets. Curious to know what the use-case for putting nodes into a public subnet is ?

**Comment by carloarteaga1** [comment]
I wasn't specifically trying to do so.  I was using the EKS quick start template that AWS provides for a new VPC here:
https://docs.aws.amazon.com/quickstart/latest/amazon-eks-architecture/welcome.html

Their quickstart was failing for me so I wasn't trying to do anything custom just trying to do the quickstarts and was just troubleshooting the best I could.

**Comment by ibisprojects** [comment]
Same issue encountered.
