### ISSUE TITLE
Allow a custom worker node AMI ID to be provided

### ISSUE THREAD

**Issue by gavincornwell** [aws-quickstart/quickstart-amazon-eks#16]
It's possible to create custom worker node AMIs using https://github.com/awslabs/amazon-eks-ami but there doesn't appear to be a parameter to allow a custom AMI to be specified for the worker nodes.

**Comment by jaymccon** [comment]
Agree that this will be very useful, will add this in an upcoming update

**Comment by RohanKurane** [comment]
@gavincornwell  @jaymccon  
Have you been able to use a custom AMI for EKS worker nodes ? 
I tried to create a worker node using the amazon linux 2 AMI. 
I then installed a few things on that worker node and then create an image of that worker node to use for future worker nodes. 
I specify the above image ID in the NodeImageId parameter on the AWS console while creating the worker node. 

However that did not work. 

Have you guys been able to use a custom AMI for worker nodes ? 

Thanks
Rohan

**Comment by gavincornwell** [comment]
@RohanKurane No, I haven't actually done this yet, just read that it is theoretically possible.

However, this is something that will we probably be attempting fairly soon.

**Comment by RohanKurane** [comment]
@gavincornwell  Can you please share the process when you do it ? I assume you will be following the hacky way in https://github.com/awslabs/amazon-eks-ami ?

**Comment by gavincornwell** [comment]
@RohanKurane Sure, no problem with sharing the process, once we get there!

**Comment by RohanKurane** [comment]
@gavincornwell  Thanks!
In the meantime, I can install CRI-O on worker nodes manually and use CRI-O as my runtime container engine.

**Comment by jaymccon** [comment]
this has been implemented in the inner node group stack with edb3821332b5b1caab528cbe3e8d73ff5b827fad will be exposed in the master templates in an upcoming patch

**Comment by qdubious** [comment]
Any update on this feature implementation?
