### ISSUE TITLE
Request: cluster autoscaler IAM role

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#163]
The cluster-autoscaler IAM role is allow only the first nodegroup (autoscaling group) to manage, but if we want to use more nodegroups within the cluster we have to manually add the new ASG to the IAM role. This could be solved if we using condition keys in the role instead of direct ASG ARNs. Something like below:

```
"Condition": {
    "StringLike": {
        "autoscaling:ResourceTag/k8s.io/cluster-autoscaler/${EksClusterName}": "*",
        "autoscaling:ResourceTag/k8s.io/cluster-autoscaler/enabled": "*"
    }
}
```

**Comment by jaymccon** [comment]
implemented in #162
