### ISSUE TITLE
Cluster autscaler cannot be deployed AWS STS request error.

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#166]
Cluster autoscaler creation failed due to this error message from the Helm lambda

<img width="767" alt="2020-07-24_15h17_41" src="https://user-images.githubusercontent.com/54439475/88395194-f8cfbc00-cdc0-11ea-8021-6fb82432c279.png">

I am using this quickstart with exicting VPC.
Any ideas what should be wrong with my cluster?

**Comment by jaymccon** [comment]
the subnet that your nodes are in requires egress internet access via a NAT Gateway in order to fetch the helm charts for the stable repo.
