### ISSUE TITLE
Bastion AMI ID cant be changed

### ISSUE THREAD

**Issue by yanivpaz** [aws-quickstart/quickstart-amazon-eks#169]
Currently custom AMI for bastion is not supported . 
I suggest to modify amazon-eks.template.yaml as below :

1. Add new parameter
   BastionAMIID:
   Type: String
   Default: ""

2.Change the current bastion default AMI
OSImageOverride: ""
To 
OSImageOverride: !Ref BastionAMIID

**Comment by yanivpaz** [comment]
PR opened
https://github.com/aws-quickstart/quickstart-amazon-eks/pull/172

**Comment by troy-ameigh** [comment]
Merged in.
