### ISSUE TITLE
Support SSM Documents being run on the bastion node

### ISSUE THREAD

**Issue by gavincornwell** [aws-quickstart/quickstart-amazon-eks#17]
We have a scenario where we need to run a "helm upgrade" command on-demand i.e. after stack creation. In our current solution we achieve this by executing an SSM Document using the Run Command functionality in Systems Manager.

In order to do this you need the instance ID of the bastion node, we currently do this by interrogating the bastion auto-scaling group. This is output from the bastion template but is not passed back up to the master/root template(s).

Would it be possible to expose the bastion ASG as a CloudFormation output or can you suggest a better way? 

For now, we'll lookup the bastion ASG from our stack using naming conventions but it would be nice to have a cleaner, stable means of accessing the ID.

NOTE: If this was supported it would also be nice if the BastionRole resource in the IAM stack had the "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM" managed policy applied so we don't have to do it in our templates.

**Comment by jaymccon** [comment]
Have you had a look at the helm install custom resource provided with this Quick Start ? 
It allows you to run helm install by declaring the helm properties in a CloudFormation template. There's an example here: https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/example-workload.template.yaml#L54-L78

**Comment by jaymccon** [comment]
from your #15 I take it you are aware of the resource. If for some reason you need to upgrade a just installed chart during stack creation there are a few other options I can think of. 

* call a stack update changing 1 property of the chart, like `Version` which will trigger the resource to update and send a `helm upgrade`
* create a modified helm custom resource that calls upgrade even on stack create

That said we'll look into passing the Bastion Instance ID back as an output, I can see many usecases for having it.

**Comment by gavincornwell** [comment]
For this particular use case we are invoking the helm upgrade after stack creation, it’s triggered by a user action so can happen at any time.

It would be awesome if you did expose the bastion instance ID!

**Comment by gavincornwell** [comment]
It occurred to me this morning that passing back the bastion ID might be problematic. 

The reason we previously used the Auto Scaling Group instead was to ensure we isolated ourselves from the scenario where a bastion node has to be re-cycled. Being in an ASG a new node will get created and hence have a different instance-ID.

**Comment by jaymccon** [comment]
ok, so will returning the asg id do the trick for you ?

**Comment by gavincornwell** [comment]
Yes, I've actually got the changes ready to go here: https://github.com/Alfresco/quickstart-amazon-eks/tree/issue17-bastion-ssm-support

I was waiting for my first pull request to be accepted and merged so that I could merge this to develop and submit another PR, I will try and do this tonight/tomorrow morning.

**Comment by gavincornwell** [comment]
PR to fix this issue: https://github.com/aws-quickstart/quickstart-amazon-eks/pull/23

**Comment by gavincornwell** [comment]
This issue can now be closed as the changes have been merged.
