### ISSUE TITLE
Using Proxy - Unable to connect to the server: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by yanivpaz** [aws-quickstart/quickstart-amazon-eks#170]
following the fix in https://github.com/aws-quickstart/quickstart-amazon-eks/issues/164  , I am getting now new error:
	
2020-07-29T21:17:57.182+03:00
{
    "timestamp": "2020-07-29 18:17:57,181",
    "level": "DEBUG",
    "location": "lambda_function.run_command:52",
    "RequestType": "Create",
    "StackId": ".../eks-stack-NodeGroupStack-MEEOPXY5UWQ/4c380be0-d1c7-11ea-9997-06b1bb61dac4",
    "RequestId": "3e751c99-6b08-4aa0-8114-40f91086d9ca",
    "LogicalResourceId": "ConfigureProxy",
    "aws_request_id": "...",
    "message": "executing command: kubectl get service/kubernetes -o jsonpath='{.spec.clusterIP}'"
}

2020-07-29T21:18:43.783+03:00
{
    "timestamp": "2020-07-29 18:18:43,783",
    "level": "ERROR",
    "location": "lambda_function.run_command:57",
    "RequestType": "Create",
    "StackId": ".../eks-stack-NodeGroupStack-MEEOPXY5UWQ/4c380be0-d1c7-11ea-9997-06b1bb61dac4",
    "RequestId": "3e751c99-6b08-4aa0-8114-40f91086d9ca",
    "LogicalResourceId": "ConfigureProxy",
    "aws_request_id": "...",
    "message": "Command failed with exit code 1, stderr: Unable to connect to the server: net/http: TLS handshake timeout\n"
}

**Comment by yanivpaz** [comment]
I think that the proxy should be unset after updating kube/config file . 

so the following fix might be needed in 
https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/functions/source/KubeManifest/lambda_function.py

import os <- new line

def create_kubeconfig(cluster_name):
    run_command(f"aws eks update-kubeconfig --name {cluster_name} --alias {cluster_name}")
    run_command(f"kubectl config use-context {cluster_name}")
    del os.environ['HTTPS_PROXY']  <- new line
    del os.environ['HTTP_PROXY'] <- new line

**Comment by jaymccon** [comment]
I'm thinking this might be because we need to exclude local traffic from being proxied. Something like:

```
NO_PROXY: !Sub '${VPCCIDR},localhost,127.0.0.1,169.254.169.254,.internal'
```

Can you confirm that you've deployed with `EKSPrivateAccessEndpoint` set to `Enabled` ? (my guess is that if you enable the public endpoint and disable private that it will work.

**Comment by yanivpaz** [comment]
I used
EKSPrivateAccessEndpoint=Enabled
EKSPublicAccessEndpoint=Disabled

I can confirm that with these parameters the current code is working 👍 
EKSPrivateAccessEndpoint=Enabled
EKSPublicAccessEndpoint=Enabled
