### ISSUE TITLE
Helm Lambda function doesn't handle failed pod deployments

### ISSUE THREAD

**Issue by gavincornwell** [aws-quickstart/quickstart-amazon-eks#19]
When one or more pods that are part of a helm chart fail to deploy i.e. ImagePullBackOff or CrashLoopBackOff, the Helm lambda function appears to poll forever. Looking at the code I can not see a Timeout/number of retries mechanism or have I missed something?

Firstly, create a stack with the EKS QuickStart. Secondly, create a stack with the [attached template](https://github.com/aws-quickstart/quickstart-amazon-eks/files/2945323/postgres-yaml.txt) and provide the lambda details as parameters. The template specifies an invalid tag name for the postgres image.

Furthermore, if you delete the IN_PROGRESS stack it appears to complete but actually leaves the helm release in-place. One of the log entries shows...

```
{
    "timestamp": "2019-03-08 09:23:40,596",
    "level": "DEBUG",
    "location": "lambda_function.run_command:32",
    "RequestType": "Delete",
    "StackId": "arn:aws:cloudformation:eu-west-1:1234567890:stack/gav-postgres/119d2a10-4181-11e9-959c-0253f164fa34",
    "RequestId": "164f75a5-f62a-4cff-a8e4-8e88342724f3",
    "LogicalResourceId": "PostgresHelmChart",
    "aws_request_id": "6fed0382-9335-49e7-a70c-709bc9f440d4",
    "message": "executing command: helm delete --home /tmp/.helm --purge gav-postgres-PostgresHelmChart-QD5E2NQY4D08"
}
```

Presumably as the helm install hasn't completed fully the physical_id is not yet set to the release name and therefore attempts to delete a non-existent helm release. After this, success is signalled to CloudFormation so the stack gets deleted.

Finally, the CloudWatch rule used for polling is also left behind so the Lambda function is continually being called.

To cleanup, the helm release and CloudWatch rule have to be deleted manually.

**Comment by jaymccon** [comment]
working on replicating this
