### ISSUE TITLE
Optional support for cluster auto-scaler?

### ISSUE THREAD

**Issue by gavincornwell** [aws-quickstart/quickstart-amazon-eks#20]
We're adding the [cluster auto-scaler](https://github.com/kubernetes/autoscaler) to our deployment using [this template](https://github.com/aws-quickstart/quickstart-amazon-eks/files/2945393/auto-scaler-yaml.txt).

However, for the auto-scaler to work a tag with a key of "k8s.io/cluster-autoscaler/enabled" has to be present on the worker nodes (see [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup) for details), the definition of which is within nested templates.

For now, we're thinking of implementing a custom resource to programatically apply the tags to the worker nodes and the worker node auto scaling group during stack creation.

As adding the auto-scaler helm chart might be something others may find useful we were wondering if you were considering adding support for popular helm charts? 

If we were to provide a pull request for this, would it get accepted or is it too specific?

**Comment by jaymccon** [comment]
this is definitely on our radar as one of the (many) optional configurations we would like to enable.

**Comment by jaymccon** [comment]
And would eagerly accept a pull request that implements this 😄

**Comment by gavincornwell** [comment]
[PR](https://github.com/aws-quickstart/quickstart-amazon-eks/pull/24) created for this issue.

**Comment by gavincornwell** [comment]
The core support for this feature has been merged in https://github.com/aws-quickstart/quickstart-amazon-eks/pull/24 but some work is still required i.e. update documentation to expose it via the master templates.

**Comment by jaymccon** [comment]
exposed in be48bb834437cdf4f80765d125aa9ad2f0daabe6. Thanks for your patience on this one
