### ISSUE TITLE
default nodegroup for clusters with windows and linux

### ISSUE THREAD

**Issue by jaymccon** [aws-quickstart/quickstart-amazon-eks#200]
At present if you provision a linux pod into a cluster with windows nodes, and don't provide a `nodeSelector` it could be scheduled on a Windows node and fail to create. This is particularly problematic for pre-packaged helm charts that often don't expose `nodeSelector`. Seeing as most common helm charts are for linux, a workaround could be to `taint` the windows hosts, so that only pods with matching `tolerations` are scheduled there. This would result in pods being scheduled on linux nodes "by default" and windows pods would need to add an additional toleration.

I'm not sure whether this makes sense for those running predominantly windows workloads, so opening this to solicit opinions.

**Comment by zgovani** [comment]
I suppose better understanding of the customer use case is needed here. I think the nodeSelector paradigm is pretty ubiquitous and it would seem like most customers that are running mixed-os clusters will be using them on all of their pods. In the case where a user is not running a mixed-os cluster, this situation will never be an issue. I'm of the opinion that unless we are seeing this as a common situation for customers, it is more of a headache annotating all the Windows pods with some toleration than just having the expectation to add a nodeSelector to your pods.
