### ISSUE TITLE
What is the purpose of the ENIs created by the Quick Start

### ISSUE THREAD

**Issue by chainhead** [aws-quickstart/quickstart-amazon-eks#201]
Can you please explain the need for **19** ENIs when the Quick Start is launched?

```bash
aws --profile eks-qs ec2 \
        describe-network-interfaces \
        --filters "Name=vpc-id,Values=vpc-id"  \
        --query 'NetworkInterfaces[*].[NetworkInterfaceId,AvailabilityZone]' --output text | wc -l
    19
```

I looked into this a bit deeper and I see the following break-up.

| Description | Count | Remarks |
| ----- | ------ | -------- |
| `AWS Lambda VPC ENI-EKS-QuickStart-KubeManifest-EKS-1YW25Z37-id` | 3 | 1 per subnet. Why are these ENI required? |
| `AWS Lambda VPC ENI-k8s-api-vpc-connector-EKS-1YW25Z37-id` | 6 | 2 per subnet. Why are these ENI required? |
| `Interface for NAT Gateway nat-id` | 3 | One ENI per subnet - this is clear |
| `aws-K8S-i-id` | 2 | One ENI per instance. However, 3 instances were requested in the CF template. What are these ENI for? |
| `Amazon EKS EKS-1YW25Z37` | 2 | What are these ENI for? |
| _No description_ | 3 | One per instance where, 3 instances were requested in the CF template. What are these ENI for? |

`EKS-1YW25Z37` is the cluster name.

**Comment by chainhead** [comment]
When I look for `InstanceOwnerId` for the network interfaces, I see few are listed as `amazon-aws`, few are listed to my account ID and others are listed to some other account ID. 

- The ENIs (12) whose owner is `amazon-aws` are the interfaces to NAT gateway or for Lambda. 
- The ones (2) with other account ID have description as `Amazon EKS EKS-1YW25Z37` and these seem to be the ENI that EKS might be using to schedule pods on. However, there are only two of these - one each for one AZ - instead of three as there are 3 AZs.
- The ones (5) with my account ID have two of them attached to EC2 instances whereas, three of them have been launched.

1. How are the instance owners `amazon-aws` and the other account ID different?
2. Why are Lambdas part of quick start?
3. Why are there only two ENIs with the other account ID - when there are three AZs?
4. Why are only two instances attached to ENI - instead of 3?

The cluster was launched with managed nodes and public + private end-points.

**Comment by jaymccon** [comment]
The eni's that start with `AWS Lambda VPC ` are lambda's that are connected to the vpc that the eks cluster is deployed in. This enables programmatic access to the kubernetes api, even if only private endpoint is enables, which allows us to do things [like this](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-prometheus.template.yaml#L11-L26) from CloudFormation templates.

`aws-K8S-i-` interfaces are created by the [vpc cni](https://github.com/aws/amazon-vpc-cni-k8s) that is the default cni for eks. AFAIK it dynamically creates eni's for pods as needed.

`Amazon EKS <CLUSTER_ID>` enis are created by the EKS service and are how your instances connect to the kubernetes api over a private ip address. There is a blog that goes into this [here](https://aws.amazon.com/blogs/containers/de-mystifying-cluster-networking-for-amazon-eks-worker-nodes/)

**Comment by chainhead** [comment]
> This enables programmatic access to the kubernetes api, even if only private endpoint is enabled, which allows us to do things like this from CloudFormation templates. 

Does that mean, those ENI exist only for the purpose of installation of certain K8S components? If so, shouldn't they be deleted once created? If not, what is the purpose of these ENIs?

> aws-K8S-i- interfaces are created by the vpc cni that is the default cni for eks. AFAIK it dynamically creates eni's for pods as needed.

Three instances were launched in three subnets; but, only two of those instances have these ENI attached. Shouldn't all instances have this ENI?

> Amazon EKS <CLUSTER_ID> enis are created by the EKS service and are how your instances connect to the kubernetes api over a private ip address. 

Thanks for the clarification.

> The 3 ENI's with `No description` are the default ENI's that get created along with the ec2 instances.

So which of the ENIs - the one with `No description` or with `aws-k8s-i-` description - are used for scheduling pods?
