### ISSUE TITLE
Failure Deploy - EKS Quickstart - FunctionStack.

### ISSUE THREAD

**Issue by jorgenivia** [aws-quickstart/quickstart-amazon-eks#202]
Currently I have a version of quickstart deployed in cloudformation and I am trying to change the instance type for the nodes and increase their disk size, but it is throwing an error in the deployment that does not allow applying the changes.

"Failed to update resource. ERROR: (truncated) Error message: [dc1f46e6-bfa4-4862-beaa-1b3c8c7da71a] Current version is no longer supported. Please upgrade to CFN-CLI 2.0 following the guide: https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/what-is-cloudformation-cli.html"

![image](https://user-images.githubusercontent.com/72526716/95388375-d0336a80-08b7-11eb-96ac-2ac80b697d24.png)

The mentioned error appears in the nested stack FunctionStack.

**Comment by jaymccon** [comment]
Unfortunately there were some upstream breaking changes that causes this for older stacks. Possible workarounds are:

* update the NodeGroup nested stack directly
* create a new stack with the latest quick start and required instance type/size
* attempt to update the qs packages in s3 before doing the stack update. How much work is invloved here depends on how old the copy you have in your bucket is (I'm assuming you have a clone of the project in your own bucket). It's most likely the `v2-final` release is what you want to update to. Once you've updated the code you can do a stack update, pointing to the updated template.

**Comment by jorgenivia** [comment]
create a new stack with the latest quick start and required instance type/size.


Thanks for the prompt response, according to what you mention as the second option, it is possible to perform a deployment with the most recent template on the same stack.

**Comment by jaymccon** [comment]
no, the 2nd option is more of a blue/green deployment, you would create a *new* stack using the latest, migrate any workloads to the new cluster, and then delete the old stack.
