### ISSUE TITLE
Template removed/renamed?

### ISSUE THREAD

**Issue by OzNetNerd** [aws-quickstart/quickstart-amazon-eks#203]
Yesterday I used https://s3.amazonaws.com/aws-quickstart/quickstart-amazon-eks/templates/amazon-eks-master.template.yaml, but today I'm getting a `"The specified key does not exist"` error. Was this an intentional change? 

If it was, is the new URL https://s3.amazonaws.com/aws-quickstart/quickstart-amazon-eks/templates/amazon-eks-entrypoint-new-vpc.template.yaml?

**Comment by jaymccon** [comment]
This was an intentional change, and you are correct on the new template file. This change was made to better comply with the [Amazon Open Source Code of Conduct](https://aws.github.io/code-of-conduct).

**Comment by OzNetNerd** [comment]
Thanks for the info & prompt reply Jay.
