### ISSUE TITLE
get an error after launch amazon-eks-entrypoint-new-vpc.template.yaml

### ISSUE THREAD

**Issue by nandexsp** [aws-quickstart/quickstart-amazon-eks#204]
I just launch with my user from python (boto3) and get this error into the CloudFormation. 
![image](https://user-images.githubusercontent.com/20782667/95460101-ccb1e900-0974-11eb-9f70-7dd287230fde.png)

The problem is when the EKSStack try to launch amazon-eks.template.yaml it fails:
![image](https://user-images.githubusercontent.com/20782667/95459543-19e18b00-0974-11eb-91f8-a5961bbad662.png)

I saw into amazon-eks-per-region-resources.template.yaml that exists a method to resolve that but I don't know if is necessary to add in the other yaml.

**Comment by troy-ameigh** [comment]
nandexsp, we typically see this when the per-region and the account level resource stack did not launch. Can you confirm that they successfully launched? They are required and are defaulted to Yes so they should have launched.

**Comment by nandexsp** [comment]
I think that this is the problem, I just disabled these:
```
{'ParameterKey': 'PerAccountSharedResources',
'ParameterValue': 'No'},
 {'ParameterKey': 'PerRegionSharedResources',
'ParameterValue': 'Yes'},
```

Thanks about your help @troy-ameigh ;)

PS: Thanks too for this amazing deployment ;)
