### ISSUE TITLE
Failed to update existing stack: Transform [accountid]::QuickStartParameterResolver failed with: Parameter /[stackname]/hashicorp/vault/Version not found

### ISSUE THREAD

**Issue by limouren** [aws-quickstart/quickstart-amazon-eks#207]
I deployed a EKS stack with this quickstart on 08/10. I tried to update the entrypoint template today (12/10) with more outputs by updating the stack template, and was met with the following error:

```
Embedded stack arn:aws:cloudformation:[region]:[accountid]:stack/[stackname]-EKSStack-[ID]/[ID] was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: Transform [accountid]::QuickStartParameterResolver failed with: Parameter /[stackname]/hashicorp/vault/Version not found
```

Judging from the error message, it seems to caused by the changes from #205. My questions:

1. Is update on an deployed stack a supported workflow? (e.g. add outputs / upgrade to a newer version of quickstart)
2. Is it possible to workaround this?

**Comment by jaymccon** [comment]
Updates will most likely be troublesome across major versions, to update to the last published v2 templates you will need to host the content from https://github.com/aws-quickstart/quickstart-amazon-eks/releases/tag/v2-final in your own s3 bucket. When updating the stack point to the template in your bucket, as well as set the `QSS3Bucket`, `QSS3KeyPrefix` and `QSS3Region` to reflect your bucket.

To upgrade major versions I suggest launching a new stack and migrating workloads from the old to the new.
