### ISSUE TITLE
V2 - Create failed.

### ISSUE THREAD

**Issue by phenri00** [aws-quickstart/quickstart-amazon-eks#208]
Using release v2.0.0

| Logical ID | Physical ID | Type | Status | Status reason
| EKS | - | AWSQS::EKS::Cluster | CREATE_FAILED | Internal Failure

Is there a more detailed error log somewhere? Checked CloudWatch logs, no obvious errors.

Same personal checked in version(git) worked yesterday.

**Comment by rc-alexg** [comment]
same here. I thought was just temporary issue related to load but for the past couple days I have been experienced the same issues without much details of the type of error.

![image](https://user-images.githubusercontent.com/41167378/95861834-fe89cd80-0d2f-11eb-9c2c-8c67541d6570.png)

**Comment by phenri00** [comment]
Same issue with the official deployment guide.

https://s3.amazonaws.com/aws-quickstart/quickstart-amazon-eks/templates/amazon-eks-entrypoint-new-vpc.template.yaml

**Comment by yanivpaz** [comment]
Hi
did you check CloudTrail API calls during the stack creation?

I got this error when the maximum session duration setting was somehow too low 
for example 
```
aws iam get-role --role-name CloudFormationRegistryResourceLogRole 
```

more information:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html#id_roles_use_view-role-max-session

**Comment by yanivpaz** [comment]
see also this link for Cloudtrail information :
https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-internal-failure-error/

**Comment by phenri00** [comment]
> Hi
> did you check CloudTrail API calls during the stack creation?
> 
> I got this error when the maximum session duration setting was somehow too low
> for example
> 
> ```
> aws iam get-role --role-name CloudFormationRegistryResourceLogRole 
> ```
> 
> more information:
> https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html#id_roles_use_view-role-max-session

"MaxSessionDuration": 3600

Also checked Cloudtrail for errors, no entries at all on that timestamp.

**Comment by phenri00** [comment]
It seems to work again. I'm using a lab account where I do various deployments, including evaluation of all available releases of quickstart-amazon-eks. Could it have something to do with resources from other deployments not being correctly purged? I discovered that there was still custom resources left in the CloudFormation registry(AWSQS::EKS::Cluster, AWSQS::Kubernetes::Helm...). I removed all of them and now apparently it's working. Don't really know if there is a connection but maybe someone else can verify this?

**Comment by rc-alexg** [comment]
@phenri00 thanks for your post. I would like to try it, could you please point to me how are you able to remove all the registered custom resources types created by the QS?

**Comment by phenri00** [comment]
> @phenri00 thanks for your post. I would like to try it, could you please point to me how are you able to remove/deregister all the registered custom resources types created by the QS?
> 
> Seems like by design the ability to delete the resource type was not incorporated on the lambda that is responsible to create custom resource: https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/functions/source/registerCustomResource/lambda_function.py#L121

You could use the cli:

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deregister-type.html

**Comment by rc-alexg** [comment]
On my case, deleting the custom resource types did not fix the `CREATE_FAILED` issue on the control plane stack. I also tried to deploy the QS EKS from the `Quick Start Reference Deployment` without success unfortunately.

**Comment by phenri00** [comment]
Tried to deploy our fork in a another account, but got following issue:

https://github.com/aws-quickstart/quickstart-amazon-eks/commit/85740bc49101651b7afa145ef8561dad46d93930  

This situation makes me really uncomfortable since we have our disaster recovery plan based on quickstart-eks. We do update our stacks to follow releases but we are not always on the latest release. We can't have arbitrary failures. 

Also found this one(not related to my specific issue, but still bad):

https://github.com/aws-quickstart/quickstart-amazon-eks/issues/202 

Is there something I'm missing here? Are releases tested frequently? Is release 2.0.0 broken?

**Comment by phenri00** [comment]
(https://aws-quickstart.github.io/quickstart-amazon-eks/)

Q. A resource type starting with AWSQS:: failed on stack create, update, or deletion.

A. These resources are AWS CloudFormation registry resource types created by the Quick Start. Logs for it are stored in Amazon CloudWatch Logs with a group prefix of /cloudformation/registry/awsqs-.

Check above stated logs if issues are caused by custom resources.

**Comment by SharpThunder** [comment]
I lost hours to this issue, i had many logs to detect issue, i deleted all unfortunately. As in #258 use below commands

> aws cloudformation deregister-type --type RESOURCE --type-name AWSQS::EKS::Cluster --version-id 00000001
>
>aws cloudformation deregister-type --type RESOURCE --type-name AWSQS::EKS::Cluster

**Comment by zikster3262** [comment]
Any news on this ?

**Comment by SharpThunder** [comment]
> Any news on this ?

Use eksctl. It is much more mature.

**Comment by zikster3262** [comment]
> 

My use-case currently requires me to use cloudformation as the main artifact to create X cluster on demands.

**Comment by ines96** [comment]
I am having exactly the same issue. 
I deploy my cloudformation stack, it creates every resource correctly. When it reaches the EKS control plane stack it is around 30 minutes creating and fails with "Internal Failure" error. 

I am not really experienced in CloudFormation but I was trying to debug this issue via Cloudwatch logs but no luck with that.

The most intriguing part is that, I have deployed the same template in another 2 accounts and it deployed perfectly with no apparent issue returned... This "Internal Failure" error is only returned in this specific account, which I find very strange.

As anyone found any resolution for this issue yet?

**Comment by troy-ameigh** [comment]
All, the internal error issue is not related to the CFN templates, but the service itself. Recommendation is when you see this try deploying in another region.
