### ISSUE TITLE
Overriding the bastion role does not work

### ISSUE THREAD

**Issue by gavincornwell** [aws-quickstart/quickstart-amazon-eks#21]
We have a need to override the role used by the bastion node. The BastionIAMRoleName parameter defined in amazon-eps.template.yaml can be used for this purpose, however doing so results in a CREATE_FAILED stack as shown in the screenshot below:

<img width="1598" alt="Screenshot 2019-03-12 at 17 11 09" src="https://user-images.githubusercontent.com/1194868/54268927-3b01b000-4574-11e9-82f4-6949fa3c6a91.png">

The problem is with the AlternativeIAMRole parameter being passed to the bastion template, the If statement is not referencing the BastionIAMRoleName parameter but is passing the hardcoded string.

**Comment by gavincornwell** [comment]
My pull request addresses the stack creation failure but unfortunately there is an additional issue.

Everything in our stack created & deployed successfully and the bastion has our custom role applied but access to the cluster is broken from the bastion. Trying "helm ls" returns the following error:

`Error: Get https://01234567890ABCDEF.yl4.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/secrets?labelSelector=OWNER%!D(MISSING)TILLER: getting credentials: exec: exit status 1`

And trying "kubectl get pods" gives the following error:

```
could not get token: AccessDenied: Access denied
	status code: 403, request id: 353f9e99-4576-11e9-b9da-e981ae5f0c78
```

This is happening because the ControlPlaneProvisionRole defined [here in amazon-eks-iam.template.yaml](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/849620a609da1a2fd52aa9e7e2261681a4caf252/templates/amazon-eks-iam.template.yaml#L102) does not allow the custom bastion role to assume the role.

When passing in a custom bastion role [the "EnableBastionRole" flag is set to false](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/849620a609da1a2fd52aa9e7e2261681a4caf252/templates/amazon-eks-iam.template.yaml#L41) meaning it skips the "Effect" statement.

I presume an acceptable fix would be to always apply the "Effect" declaration and either use the custom role ARN or the ARN of the bastion role created by the template. 

However, currently only the custom bastion role name is passed through so we would have to also pass through the custom bastion role ARN as well which starts getting a bit messy i.e. what happens if someone passes the role name but not the role ARN.

Alternatively, rather than allowing a custom role to be specified the bastion role could be exposed via an Output like the NodeInstanceRole is in amazon-eks.template.yaml, thus allowing customers to add their own custom policies in their templates.

Please advise on what you think the best way forward is.

**Comment by jaymccon** [comment]
Passing your custom role to the [AdditionalEKSAdminArns](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks.template.yaml#L31) parameter should let you get the role authorized with k8s rbac.

**Comment by gavincornwell** [comment]
Ah yes, of course, thank you for the suggestion!

**Comment by gavincornwell** [comment]
I think this issue can now be closed as the changes have been merged.
