### ISSUE TITLE
Support 1.18

### ISSUE THREAD

**Issue by yanivpaz** [aws-quickstart/quickstart-amazon-eks#212]
Hi
EKS 1.18 is out 
https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-eks-supports-kubernetes-version-1-18/

As we have a new version every 3 months - is there any simple procedure/checklist  to perform the upgrade?
 
- EKS  control  plan
- EKS worker template
- EKS worker ami ( using ssm parameter so should be automatically retrieved )
- Addons  upgrades - cluster auto scalar, external dns 
- Upgrade clients    - helm3 ,  kubectl

**Comment by bogdan-kovalev** [comment]
Hey @jaymccon , the k8s version 1.19 is out. When can we expect the support in awsqs?
