### ISSUE TITLE
No transform named <AccountID>::QuickStartParameterResolver found.

### ISSUE THREAD

**Issue by kn0xyland** [aws-quickstart/quickstart-amazon-eks#222]
Hi EKS Team,

I am probably doing something completely newb but I am trying to deploy the v3 QuickStart and am getting an error from one of the  nested stacks "EKSStack" during deployment. I have deployed the Advanced stack prior to deploying the "use existing VPC template". 

Some background, I have downloaded the v3 zip and copied to my s3 bucket (and updated the QSS3BucketName, QSS3KeyPrefix & QSS3BucketRegion parameter on the existing VPC entrypoint template so it points to my s3 location). I should mention I have the v2 stack deployed in the same account, however the v2 deployment is bound to a different VPC within the same account. 

This deployment (v3) is going into the same account ID/Region, but a different VPC (existing VPC).  I have therefore set the following to "No" as advised, PerAccountSharedResources & PerRegionSharedResources. However, I feel like I may have missed something as I am getting the following error from CloudFormation upon execution:

EKSStack: "No transform named <AccountID>::QuickStartParameterResolver found."

Many thanks for your time!

**Comment by mbarbine** [comment]
I am also experiencing this issue.

**Comment by gargana** [comment]
The advice from the deployment guide around "PerAccountSharedResources" & "PerRegionSharedResources" holds only for additional deployments of the current version(v3). These did not exist in v2. Please try the deployments with those parameter values set to "Yes".

**Comment by kn0xyland** [comment]
That did the trick! Thank you :)
