### ISSUE TITLE
Cluster Autoscaler enabled causes failure

### ISSUE THREAD

**Issue by dayyehm** [aws-quickstart/quickstart-amazon-eks#242]
When deploying the main template in the solution : 
https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks.template.yaml

creates first time ok but if we try to create another cluster it fails with the error : 
The policy None already exists on the role eks-quickstart-managednodeinstance

**Comment by prat0881** [comment]
I am having the same issue.
