### ISSUE TITLE
custom resource fails with: __init__() got an unexpected keyword argument 'previousSystemTags' (TypeError)

### ISSUE THREAD

**Issue by yiuc** [aws-quickstart/quickstart-amazon-eks#246]
I tried to use the quickstart script to provision the EKS cluster. The error happens on create ALBClusterRole in [amazon-eks-alb-ingress.template.yaml](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-alb-ingress.template.yaml). Look like the plugin running some problem like [perivous issue](https://github.com/aws-quickstart/quickstart-amazon-eks/pull/243) it returns unexpected keyword argument. I think in another repo using same plugin also have the [similar issue](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/136).
 
https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/136

![image](https://user-images.githubusercontent.com/5475929/98941329-5ed67f80-2527-11eb-9457-345c22d436aa.png)

**Comment by aws-Ninja** [comment]
As tested today, I am still seeing different but similar message from `ALBClusterRole` said `__init__() got an unexpected keyword argument 'snapshotRequested' (TypeError)` when using quickstart script to provision the EKS cluster, is this something else?

**Comment by kn0xyland** [comment]
I also received this, I have logged with AWS about this issue who suspect it could be a problem with pagination within the Lambda function. I tested this morning in a brand new environment and got it again. I am attempting to deploy this with ALB disabled to see if enabling it through another stack up date allow it to complete. 

Any ETA?

**Comment by yiuc** [comment]
> As tested today, I am still seeing different but similar message from `ALBClusterRole` said `__init__() got an unexpected keyword argument 'snapshotRequested' (TypeError)` when using quickstart script to provision the EKS cluster, is this something else?

Did you checkout the latest updated quickstart repo? I saw the source have been updated to 2.1.4 It is fixed my issue. I guess you may not have the updated zip in your lambda. You can try to run the cft in a fresh environment to verify that
