### ISSUE TITLE
amazon-eks-load-balancer-controller.template.yaml may not able to use in China region

### ISSUE THREAD

**Issue by yiuc** [aws-quickstart/quickstart-amazon-eks#265]
I tried to use the latest master branch to provision the EKS in china region however I found that the amazon-eks-load-balancer-controller image isn't able to pull as  **no basic auth credentials**. I guess it is because china region can't reach the global endpoint

I have created an issue on the eks-charts https://github.com/aws/eks-charts/issues/398

![](https://user-images.githubusercontent.com/5475929/102882895-12695280-448a-11eb-896d-fd3e4f4474ad.png)

https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-load-balancer-controller.template.yaml

**Comment by yiuc** [comment]
I found the ecr image list in https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.1.0. It is include all of the region. The amazon-eks-load-balancer-controller.template.yaml should include the ecr list in parm. I will try on my side.

**Comment by jaymccon** [comment]
Can confirm same for `us-gov-` partition. Looking into the fix in https://github.com/yiuc/quickstart-amazon-eks/commit/3deb6cd4e3c50c6a51e3aa20c9d420de37c0fdd7
