### ISSUE TITLE
[Feature request] Deploy chart from S3

### ISSUE THREAD

**Issue by schottsfired** [aws-quickstart/quickstart-amazon-eks#268]
I wish for the **[Repository url](https://github.com/aws-quickstart/quickstart-helm-resource-provider/blob/308badf0634403ae71d06753ed5cc1821c811b11/docs/README.md#repository)** to support `S3://` URLs in addition to `HTTP(S)://` URLs, to allow the EKS Quick Start to deploy "offline" charts in S3.

**Comment by schottsfired** [comment]
Did some digging and found that this is [already supported](https://github.com/aws-quickstart/quickstart-helm-resource-provider/blob/d6a559f3d3a4a7d4e34e539299e539f470a30e70/cmd/resource/utils_test.go#L149-L160)? I'll have to give it a try.

**Comment by schottsfired** [comment]
Already works!

**Comment by yanivpaz** [comment]
ecr already support helm charts
