### ISSUE TITLE
PreReqs stack fails

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#277]
Hello!

When I'm running the latest version, I got this error message from CF:
My account CloudFormation registry is empty, so there aren't any previous version of these account and regional resources.
```
Failed to create resource. Exception: An error occurred (AccessDenied) when calling the DescribeStacks operation: User: arn:aws:sts::655531603756:assumed-role/eks-AutoDetectSharedResources-1SHWIN58-PreReqsRole-1RETPI7AQRO1U/eks-AutoDetectSharedResources-1SHW-PreReqsFunction-1O220B18AS2PQ is not authorized to perform: cloudformation:DescribeStacks with an explicit deny
```
What should be the problem?

**Comment by Alex-Murr** [comment]
Hi @tomiszili 

I just got the same error, were you able to solve it?

Thanks in advance!

**Comment by kwit75** [comment]
same here:
Embedded stack arn:aws:cloudformation:us-west-2:25:stack/Amazon-EKS-AutoDetectSharedResources-1TKMA4LIUKBOE/bf1b4220-ebfd-11eb-af7a-024a063cb5a5 was not successfully created: The following resource(s) failed to create: [PreReqs].

**Comment by troy-ameigh** [comment]
@el2ro was your issue based on Region Restrictions, by your company.

**Comment by bulat-khusnimardanov** [comment]
> @el2ro was your issue based on Region Restrictions, by your company.

Hi Troy,
We have the same issue caused by the Control Tower region deny guardrail (https://docs.aws.amazon.com/controltower/latest/userguide/data-residency-guardrails.html#primary-region-deny-policy).
PreReqsFunction calls describe_stacks (not allowed by the guardrail) against all regions returned by the describe_regions, which does not take into account restrictions imposed by the guardrail.

**Comment by bulat-khusnimardanov** [comment]
> @el2ro was your issue based on Region Restrictions, by your company.

Hi Troy,

We have the same issue caused by the region deny guardrail (https://docs.aws.amazon.com/controltower/latest/userguide/region-deny.html) enabled.

**Comment by bulat-khusnimardanov** [comment]
> That might be it. We have restricted some regions, so it might be causing this. I wonder if there is some easy way around it?

Workaround is to avoid AutoDetectSharedResources deployment, to do so, you must explicitly set PerAccountSharedResources and PerRegionSharedResources parameters to Yes, if you deploy this quick start for the first time, or to No otherwise.

**Comment by troy-ameigh** [comment]
this should be resolved with lastest updates
