### ISSUE TITLE
What permissions does my IAM role need?

### ISSUE THREAD

**Issue by martinffx** [aws-quickstart/quickstart-amazon-eks#28]
I'm trying to deploy this stack but it keeps failing with permission issues:

```
  | 14:02:04 UTC+0200 | ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | Martin-Test-Amazon-EKS |  
  | 14:02:03 UTC+0200 | DELETE_COMPLETE | AWS::CloudFormation::Stack | VPCStack |  
  | 14:01:44 UTC+0200 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | Martin-Test-Amazon-EKS | The following resource(s) failed to create: [VPCStack]. . Rollback requested by user.
  | 14:01:44 UTC+0200 | CREATE_FAILED | AWS::CloudFormation::Stack | VPCStack | S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
  | 14:01:43 UTC+0200 | CREATE_IN_PROGRESS | AWS::CloudFormation::Stack | VPCStack |  
  | 14:01:31 UTC+0200 | CREATE_IN_PROGRESS | AWS::CloudFormation::Stack | Martin-Test-Amazon-EKS | User Initiated
```
I've tried without setting an IAM role (I assume it uses the current user, who is an admin) and with an IAM that has the admin access policy attached.

I'm not sure why it is failing?

**Comment by gavincornwell** [comment]
It sounds like an S3 permissions error, how are you deploying the EKS QuickStart? Are you copying the files to an S3 bucket that your user doesn't have access to?

Is this your own account or a company one that might be subject to permission restrictions?

**Comment by martinffx** [comment]
I'm using the default one stored on S3, I didn't know I was supposed to make a copy of it?

I'm the account administrator.

**Comment by gavincornwell** [comment]
No, you don't **have** to make a copy of it I was just speculating that may have been the cause if you had.

How are you deploying the stack? From the command line or console?

**Comment by martinffx** [comment]
console

**Comment by gavincornwell** [comment]
Hmm, that does sound strange in that case. I've just tested in my account and the stack appears to be creating as expected for me.

Are you overriding the S3 bucket name or prefix parameters?

**Comment by martinffx** [comment]
I am

**Comment by gavincornwell** [comment]
Ah OK, unless you have customised the templates you should leave the bucket name as "aws-quickstart" and the prefix as "quickstart-amazon-eks/".

**Comment by martinffx** [comment]
Thank you, that seems to have got me further along but still no cigar. 
I now get this issue when launching the stack in `us-east2`: 

```
12 Apr 2019 07:09:39	Amazon-EKS	
ROLLBACK_COMPLETE	-
12 Apr 2019 07:09:38	VPCStack	
DELETE_COMPLETE	-
12 Apr 2019 07:07:22	VPCStack	
DELETE_IN_PROGRESS	-
12 Apr 2019 07:07:21	EKSStack	
DELETE_COMPLETE	-
12 Apr 2019 06:51:02	EKSStack	
DELETE_IN_PROGRESS	-
12 Apr 2019 06:50:47	Amazon-EKS	
ROLLBACK_IN_PROGRESS	The following resource(s) failed to create: [EKSStack]. . Rollback requested by user.
12 Apr 2019 06:50:46	EKSStack	
CREATE_FAILED	Embedded stack arn:aws:cloudformation:us-east-2:320704657202:stack/Amazon-EKS-EKSStack-11LSGRDG1KQOK/d96a8ee0-5ceb-11e9-ba29-020cf0d94894 was not successfully created: The following resource(s) failed to create: [NodeGroupStack].
12 Apr 2019 06:26:04	EKSStack	
CREATE_IN_PROGRESS	Resource creation Initiated
12 Apr 2019 06:26:04	EKSStack	
CREATE_IN_PROGRESS	-
12 Apr 2019 06:25:59	VPCStack	
CREATE_COMPLETE	-
12 Apr 2019 06:21:55	VPCStack	
CREATE_IN_PROGRESS	Resource creation Initiated
12 Apr 2019 06:21:54	VPCStack	
CREATE_IN_PROGRESS	-
12 Apr 2019 06:21:48	Amazon-EKS	
CREATE_IN_PROGRESS	User Initiated
```

And some sort of VPC issue when trying to launch in `eu-west1`:

```
11 Apr 2019 12:03:09	Amazon-EKS	
ROLLBACK_COMPLETE	-
11 Apr 2019 12:03:08	VPCStack	
DELETE_COMPLETE	-
11 Apr 2019 12:02:05	VPCStack	
DELETE_IN_PROGRESS	-
11 Apr 2019 12:02:01	Amazon-EKS	
ROLLBACK_IN_PROGRESS	The following resource(s) failed to create: [VPCStack]. . Rollback requested by user.
11 Apr 2019 12:02:00	VPCStack	
CREATE_FAILED	Embedded stack arn:aws:cloudformation:eu-west-1:320704657202:stack/Amazon-EKS-VPCStack-9DWZFI3K8W9V/772a2d70-5c51-11e9-8bb6-06805a56c612 was not successfully created: The following resource(s) failed to create: [PrivateSubnet3ARouteTableAssociation, NAT1EIP, NAT2EIP, PublicSubnet1RouteTableAssociation, NAT3EIP, PrivateSubnet2ARouteTableAssociation, PublicSubnetRoute, PrivateSubnet1ARouteTableAssociation, PublicSubnet2RouteTableAssociation].
11 Apr 2019 12:00:58	VPCStack	
CREATE_IN_PROGRESS	Resource creation Initiated
11 Apr 2019 12:00:56	VPCStack	
CREATE_IN_PROGRESS	-
11 Apr 2019 12:00:49	Amazon-EKS	
CREATE_IN_PROGRESS	User Initiated
```

**Comment by gavincornwell** [comment]
Oh dear, you're not having much luck are you!

Is there an explanation for the failure? If you expand the row that reports the failure in the CloudFormation console there is normally an error message giving an indication of what the underlying problem is. You may also need to examine the events of the nested stacks to find the details.

My guess is that you may be running into service limits i.e. the number of VPCs.

**Comment by jaymccon** [comment]
As Gavin mentioned you will need to look at the events for the VPC stack to get to the cause of the failure.

**Comment by MMichael-S** [comment]
Sorry for reply to a closed issue.
But I met the same error "S3 error: Access Denied" and found this by Google.
It confused me if I must leave the bucket name as "aws-quickstart" and the prefix as "quickstart-amazon-eks/"? 
I think these parameter can be updated to my own S3 bucket because they are updatable~

**Comment by brentcetinich** [comment]
For me it was the NAT Gateway service quota , I already had 2 so the failure was resolved by deleting the unnecessary NAT gateways I already had and also releasing the elastic IP back to AWS.
