### ISSUE TITLE
Status of releases.

### ISSUE THREAD

**Issue by phenri00** [aws-quickstart/quickstart-amazon-eks#289]
Lastest release is from 8 Oct 2020.  We have been tailing releases for updating our codebase. Now we need to upgrade to 1.18.

What is the recommended way to upgrade? Checkout latest master?

**Comment by Alex-Murr** [comment]
Hi, 

I'd be interested to know this too. Is it safe/recommended to checkout from master to upgrade to 1.18?

Thanks!

**Comment by phenri00** [comment]
Will there be anymore releases in the future or do you have something else in mind?

**Comment by troy-ameigh** [comment]
Current QuickStart in the main branch is on 1.19 and includes 1.18
