### ISSUE TITLE
LoadBalancerControllerServiceAccount fails to delete when tearing down stack

### ISSUE THREAD

**Issue by mttwise** [aws-quickstart/quickstart-amazon-eks#306]
The LoadBalancerControllerServiceAccount says ResourceTimedOut as the reason.  On subsequent delete attempts, it shows InternalFailure.  This is most likely because the cluster continues to tear down despite the first failure so the kubectl-apply lambda no longer exists on retry.

![image](https://user-images.githubusercontent.com/24458226/113334552-74d3b980-92e9-11eb-8afb-fd1fdd555695.png)

**Comment by jl-ui** [comment]
I can confirm I have the same issue.
Could this be solved manually?
