### ISSUE TITLE
Cannot create more than 20 EKS Clusters in the same account using EKS Quickstart

### ISSUE THREAD

**Issue by mttwise** [aws-quickstart/quickstart-amazon-eks#310]
When ClusterAutoScaler is enabled (and possibly other settings) an inline policy gets added to the eks-quickstart-ManagedNodeInstance and eks-quickstart UnmanagedNodeInstance roles.  After ~20 EKS clusters are created, the inline policies exceed the max character limit for an IAM role.  Since IAM roles are shared at the account level, this means that no more than 20 clusters can be deployed globally.
![image](https://user-images.githubusercontent.com/24458226/115249562-542fa000-a0ee-11eb-8784-4b0b33b9907f.png)

![image](https://user-images.githubusercontent.com/24458226/115249986-c4d6bc80-a0ee-11eb-9d43-67bc2e6dc212.png)

**Comment by bogdan-kovalev** [comment]
I think you should not attach any policies to `ManagedNodeInstance` and `UnmanagedNodeInstance` roles, because they are shared across all stacks.
If you need some additional permissions, you need a separate role for that. And that role has to be used to give those perms.

**Comment by mttwise** [comment]
I am not attaching these policies directly, they are being attached automatically by setting the ClusterAutoScaler parameter to "Enabled" when deploying.

![image](https://user-images.githubusercontent.com/24458226/116091450-6ff4f200-a66a-11eb-9567-9aed43f59375.png)
