### ISSUE TITLE
From where does awsqs-kubernetes-resource-apply-proxy-{cluster_name} function updates its lambda code ?

### ISSUE THREAD

**Issue by sudhfree** [aws-quickstart/quickstart-amazon-eks#311]
If we look at the vpc.py file inside the "**fundtions/packages/awsqs_kubernetes_apply_vpc.zip**" lambda  , then the vpc.py file inside the  **awsqs_kubernetes_resource** folder is calling the following code:
`while True:`
            `try:`
                `with open("./awsqs_kubernetes_resource/**vpc.zip**", "rb") as zip_file:`
                    `lmbd.update_function_code(`
                        `FunctionName=f"awsqs-kubernetes-resource-apply-proxy-{cluster_name}",`
                        `ZipFile=zip_file.read(),`
                    `)`
                `break`
            `except lmbd.exceptions.ResourceConflictException as e:`
                `if "The operation cannot be performed at this time." not in str(e):`
                    `raise`
                `LOG.error(str(e))`
                `time.sleep(10)`

My query is where is it getting the vpc.zip file , cause inside the  "awsqs_kubernetes_apply_vpc/awsqs_kubernetes_resource/" **there is no "vpc.zip" is present.**

Reason for question: **I want to change the vpc.py file to include the custom path in the assumed IAM role. But beacause it is updating the code due to which my changes are getting overridden.**

**NOTE:  I copied complete code and templates from aws-quickstart bucket to my private s3 bucket .**

It is very critical to my eks setup in the project. Thanks any ways.

Thanks,

**Comment by troy-ameigh** [comment]
As part of the publishing process the zip files are packaged and pushed to the publishing bucket. If you have forked the repo, you will need to do the following to get the packages to build and then you can publish to your own bucket.

From root of repo:

$> make build
$> BUCKET=<Bucket Name> REGION=<region bucket was created in> make publish
