### ISSUE TITLE
awsqs-kubernetes-resource-apply-proxy-{cluster_name}: must have length less than or equal to 64

### ISSUE THREAD

**Issue by bogdan-kovalev** [aws-quickstart/quickstart-amazon-eks#314]
We encounetred an error in our environment:

> validation error detected: Value 'awsqs-kubernetes-resource-apply-proxy-script-pr-242-29-aws-mt-49aa7b' at 'functionName' failed to satisfy constraint: Member must have length less than or equal to 64

Problem:
The prefix: `awsqs-kubernetes-resource-apply-proxy-` takes 38 chars, leaving only 26 (less than a half characters for the `{cluster_name}`. This adds an artificial constraint to the `EKSClusterName` stack parameter of the `amazon-eks-controlplane.template.yaml` which is not documented anywhere and there is no validation rule for that.

Expected:
1. The `EKSClusterName` parameter needs a validation rule.
2. The `awsqs-kubernetes-resource-apply-proxy-` prefix has to be shrunk in length.

**Comment by bogdan-kovalev** [comment]
Our taskcat CI cannot pass because of this issue as well because Taskcat generates pretty long names:

> Exception caught An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: 1 validation error detected: Value 'awsqs-kubernetes-resource-apply-proxy-tCaT-quickstart-test-new-vpc-af942dc86ae24a6282d72d3e6785a314' at 'functionName' failed to satisfy constraint: Member must have length less than or equal to 64

Any idea how to overcome this?

**Comment by gargana** [comment]
In **.taskcat.yml** you can set 
```
project:
  shorten_stack_name: true
```
Let me know if that helps?

**Comment by bogdan-kovalev** [comment]
@gargana , it did help with taskcat, thanks.
