### ISSUE TITLE
Minimum required permissions to deploy the quickstart

### ISSUE THREAD

**Issue by mbghdev** [aws-quickstart/quickstart-amazon-eks#315]
Hello, I'm trying to create custom policy with the minimum required permissions to just deploy this CF template.

the idea would be to have a base policy where all users would be added and then have separate policies for each of the components we want to run in CF (EKS, RDS, etc).

Do you have the set of permissions required to run this one? I've tried adding all the EKS predefined policies but it's throwing errors while trying to work with the embedded templates: _AutoDetectSharedResources_ and _AdvancedConfigDefaultsStack_

I'm pretty sure all predefined EKS policies are not required hence the request of the specific set of permissions needed to run this.

thanks in advance and great work AWS quickstart team!

**Comment by troy-ameigh** [comment]
We cannot do this as we don't have a good way of knowing which pieces a customer will deploy. As we add new features, we would need to be constantly adjusting. Unfortunately, this is not an easy answer, as it is high dependent on user inputs during launch.
