### ISSUE TITLE
Bastion support for t4g instance types

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#319]
Please add support for t4g instance family for the bastion host.
It will be more cost effective than the t2/t3 types.

Thanks in advance!

**Comment by troy-ameigh** [comment]
I have created this issue in the Linux Bastion QuickStart repo: [https://github.com/aws-quickstart/quickstart-linux-bastion/issues/132](https://github.com/aws-quickstart/quickstart-linux-bastion/issues/132)
