### ISSUE TITLE
Loadbalancer controller policy mismatch.

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#320]
Hi all!

The loadbalancer controller helm chart uses the latest repo of the loadbalancer controller, but the minimal[ IAM policy](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json) is changes as well. Please either fix the helm version or update the iam policy of the template.

Thanks in advance!

**Comment by prashilgupta** [comment]
I made the following change which works

$ git diff
diff --git a/templates/amazon-eks-load-balancer-controller.template.yaml b/templates/amazon-eks-load-balancer-controller.template.yaml
index ab7c931..4c134e8 100644
--- a/templates/amazon-eks-load-balancer-controller.template.yaml
+++ b/templates/amazon-eks-load-balancer-controller.template.yaml
@@ -92,6 +92,7 @@ Resources:
                 - 'iam:CreateServiceLinkedRole'
                 - 'ec2:DescribeAccountAttributes'
                 - 'ec2:DescribeAddresses'
+                - 'ec2:DescribeAvailabilityZones'
                 - 'ec2:DescribeInternetGateways'
                 - 'ec2:DescribeVpcs'
                 - 'ec2:DescribeSubnets'
@@ -99,6 +100,8 @@ Resources:
                 - 'ec2:DescribeInstances'
                 - 'ec2:DescribeNetworkInterfaces'
                 - 'ec2:DescribeTags'
+                - 'ec2:GetCoipPoolUsage'
+                - 'ec2:DescribeCoipPools'
                 - 'elasticloadbalancing:DescribeLoadBalancers'
                 - 'elasticloadbalancing:DescribeLoadBalancerAttributes'
                 - 'elasticloadbalancing:DescribeListeners'
@@ -212,6 +215,15 @@ Resources:
                 - 'elasticloadbalancing:RegisterTargets'
                 - 'elasticloadbalancing:DeregisterTargets'
               Resource: !Sub 'arn:${AWS::Partition}:elasticloadbalancing:*:*:targetgroup/*/*'
+            - Effect: Allow
+              Action:
+                - 'elasticloadbalancing:AddTags'
+                - 'elasticloadbalancing:RemoveTags'
+              Resource:
+                - !Sub 'arn:${AWS::Partition}:elasticloadbalancing:*:*:listener/net/*/*/*'
+                - !Sub 'arn:${AWS::Partition}:elasticloadbalancing:*:*:listener/app/*/*/*'
+                - !Sub 'arn:${AWS::Partition}:elasticloadbalancing:*:*:listener-rule/net/*/*/*'
+                - !Sub 'arn:${AWS::Partition}:elasticloadbalancing:*:*:listener-rule/app/*/*/*'
             - Effect: Allow
               Action:
                 - 'elasticloadbalancing:SetWebAcl'
@@ -243,6 +255,7 @@ Resources:
       Namespace: kube-system
       Repository: https://aws.github.io/eks-charts
       Chart: aws-load-balancer-controller
+      Version: 1.2.0
       Values:
         clusterName: !Ref EksClusterName
         serviceAccount.create: false

**Comment by johan-ripoll** [comment]
Still not updated. I had to fix this manually.
