### ISSUE TITLE
Feature Request: allow adding tags to nodegroup launch template via parameter

### ISSUE THREAD

**Issue by lennartt** [aws-quickstart/quickstart-amazon-eks#333]
Add an optional entrypoint parameter to allow adding TagSpecifications in AWS::EC2::LaunchTemplate LaunchTemplateData

**Comment by jaymccon** [comment]
not quite sure how we'd do this as TagSpecifications is an array of objects, and cfn parameters can only take strings as inputs. arrays are particularly troublesome, as cfn can split a comma separated string into a list, but provides no way to know how long the list is, or to loop through the list values.

**Comment by lennartt** [comment]
I think you're right, I also don't see a way to do this now that I think of it (disregarding the use of jinja or an additional parameter specifying the number of tags)...
