### ISSUE TITLE
BastionInstanceType not found.

### ISSUE THREAD

**Issue by olegk00** [aws-quickstart/quickstart-amazon-eks#339]
Hello, 

I've been trying to create an EKS cluster with a new VPC using template "templates/amazon-eks-entrypoint-new-vpc.template.yaml, with bastion provisioning enabled, however getting below error. It seems BastionInstanceType parameter is not defined?

ResourceLogicalId:EKSStack, ResourceType:AWS::CloudFormation::Stack, ResourceStatusReason:Embedded stack arn:aws:cloudformation:us-east-2:XXXXXXXXXX:stack/StackSet-devenv-eks-with-vpc-v1-XXXXXXXXX-XXXXXXXX-EKSStack-XXXXXX/XXXXXXXXXXXXXX was not successfully created: Transform XXXXXXXXXX::QuickStartParameterResolver failed with: Parameter /devenv-eks-with-vpc-v1_config-v1/bastion/BastionInstanceType not found.

**Comment by troy-ameigh** [comment]
olegk00 are you entering any values for the parameter "ConfigSetName"?? Or are you taking the default?

**Comment by olegk00** [comment]
I was entering a value in ConfigSetName.
By the way, I was able to get around this issue by running the "advanced
settings" template first, which created config parameter
BastionInstanceType. I guess that's required in order to be able to create
a bastion with the way templates are set up now.

**Comment by troy-ameigh** [comment]
So if you enter a ConfigSetName it assumes that your ran advanced settings template first. If you leave the ConfigSetName blank (which is default), it will automatically run the advanced settings template, there by giving you all the defaults.
