### ISSUE TITLE
KubeManifest error on update of CloudFormation stack

### ISSUE THREAD

**Issue by dcaruana** [aws-quickstart/quickstart-amazon-eks#34]
When a CloudFormation template contains a resource of type "Custom::KubeManifest" it is not possible to update the stack as any KubeManifest resource will error with...

Command failed with exit code 1, stderr: Error from server (NotFound): configmaps "aws-auth" not found

This is due to running a 'kubectl apply' command that does not return json.

**Comment by jaymccon** [comment]
#35
