### ISSUE TITLE
RBAC Role is not deleted for the created cluster.

### ISSUE THREAD

**Issue by KarthikContainers** [aws-quickstart/quickstart-amazon-eks#340]
Steps followed:

1. Install the cluster using quickstart cloudformation template.
2. Delete the cloudfromation stack.

While the cluster is being deleted RBACRole is not deleted. This looks like an issue in a new [template](https://github.com/aws-quickstart/quickstart-amazon-eks/pull/301/commits/c4cb60cd05bc08e3485da9ae5d41630a571cf654). 

![image (7)](https://user-images.githubusercontent.com/80087885/125525700-2ae0e4dc-aad9-4fa5-a400-6100f4719133.png)
![image (8)](https://user-images.githubusercontent.com/80087885/125525722-ae91adfb-81c8-40e4-8104-6a2ba111da99.png)

**Comment by tlindsay42** [comment]
Fixed at some point. Not able to reproduce.
