### ISSUE TITLE
BastionBootstrapScript not found

### ISSUE THREAD

**Issue by jorgenivia** [aws-quickstart/quickstart-amazon-eks#347]
Hello,

I have tried to upgrade an EKS cluster however the error appears below. It seems that the BastionBootstrapScript parameter is undefined?

Embedded stack arn:aws:cloudformation:us-east-1:XXXXXXXXXXX:stack/Amazon-EKS-Pro-EKSStack-XXXXXXXXXXX/XXXXXXXXXXXX was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: Transform XXXXXXXXXXX::QuickStartParameterResolver failed with: Parameter /Amazon-EKS-Pro/bastion/BastionBootstrapScript not found

**Comment by troy-ameigh** [comment]
This is should be good
