### ISSUE TITLE
Production readiness of quickstart-amazon-eks ? 

### ISSUE THREAD

**Issue by SaltedEggIndomee** [aws-quickstart/quickstart-amazon-eks#36]
Hi guys,

Is the quickstart for EKS evaluated as production ready?? 

In terms of security and manageability. 

Anyways great work in simplifying stuffs for new users to EKS!!

**Comment by jaymccon** [comment]
While AWS Quick Start's aim to be production ready there is no formal evaluation process as such. Be sure to thoroughly validate the Quick Start against your own requirements and criteria for production infrastructure (be sure to let us know if you find anything lacking). A fairly common practice is for customers with specific compliance requirements is to use the Quick Start as a base and then overlay their requirements on that. For more info on how to do that you can have a look at the [Make it your own](https://aws-quickstart.github.io/option1.html) section of the AWS Quick Start contributors guide.
