### ISSUE TITLE
Allow Modifying Cluster Endpoint Access

### ISSUE THREAD

**Issue by nicdoye** [aws-quickstart/quickstart-amazon-eks#37]
I'd like to enable private access for the Kubernetes API server endpoint, and completely disable public access. I believe this would be possible by adding the ability to alter the values of `EndpointPublicAccess` & `EndpointPrivateAccess` in amazon-eks-controlplane.template.yaml 

See https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html 

I can start working on this feature/enhancement if you are not already doing so.

**Comment by jaymccon** [comment]
we haven't started work on this as of yet, waiting for CloudFormation support for this feature to arrive. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-cluster-resourcesvpcconfig.html

Could be done by custom resource in the meantime, but native cfn support would be better long term

**Comment by nicdoye** [comment]
Ah, thanks @jaymccon , I'd missed that there wasn't CFN support for this yet.

**Comment by jaymccon** [comment]
https://github.com/aws/containers-roadmap/issues/242

**Comment by jaymccon** [comment]
Gave up on waiting for #242 and we've implemented this in a CFN Registry resource
