### ISSUE TITLE
EksClusterResource should be replaced by the AWS::EKS::Cluster resource

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#376]
Hi!

The AWS native Cloudformation resource for the [EKS cluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html) should replace the EksClusterResource.
I guess only the aws-auth configmap modification option differs.

**Comment by troy-ameigh** [comment]
We are doing this, as the EKSClusterResource provides richer functionally than the AWS::EKS::Cluster. As the AWSQS::EKS::Cluster is housed with in CFN. 

https://github.com/aws-quickstart/quickstart-amazon-eks-cluster-resource-provider
