### ISSUE TITLE
Context deadline exceeded error from Helm Lambda

### ISSUE THREAD

**Issue by gavincornwell** [aws-quickstart/quickstart-amazon-eks#38]
We've had three occurrences of the following error this week during the deletion of stacks that were 100% reliable for the last few weeks.

<img width="1614" alt="Screenshot 2019-05-16 at 09 53 32" src="https://user-images.githubusercontent.com/1194868/57875419-d3cdd980-780a-11e9-9950-426eff8d3469.png">

**Comment by jaymccon** [comment]
@gavincornwell I'm looking at putting some retries in place to fix this, are you able to share any logs from the helm lambda function? I would like to confirm it'll be addressing the failures you ran into.

**Comment by jaymccon** [comment]
retries added in e03cd1cc9ff8200725d0257217ff456ad43b0670
