### ISSUE TITLE
Kubectl Apply Lambda is being called multiple times leading to deployment failure

### ISSUE THREAD

**Issue by mttwise** [aws-quickstart/quickstart-amazon-eks#384]
Sometimes the apply lambda gets triggered multiple times causing the same manifest to be fed through twice. The issue appears to be intermittent, but has occurred more often recently. 50% of my deployments are seeing this issue on various stacks and have to be retried

The duplicate lambda run leads to an error like:
```
[ERROR] Exception: Error from server (AlreadyExists): error when creating "/tmp/manifest.yaml": namespaces "amazon-cloudwatch" already exists
```

Here are some sample logs...note that each lambda run was ~2 minutes apart and was triggered by the same CloudFormation stack deployment.

First Run of Lambda (Success)
![image](https://user-images.githubusercontent.com/24458226/142693316-711f1559-452b-48c1-acab-dff74d643e1d.png)

Second Run of Lambda (Failure)
![image](https://user-images.githubusercontent.com/24458226/142693303-6bed1e6a-9122-4e2d-8e0e-957a987292a5.png)

Stack Events:
![image](https://user-images.githubusercontent.com/24458226/142695341-6c65a625-7f40-49aa-9204-bfb6207d3fc2.png)

**Comment by tlindsay42** [comment]
Resolved at some point. Current end-to-end tests where `EKSPublicAccessEndpoint` is set to `Disabled`, such as: https://github.com/aws-quickstart/quickstart-amazon-eks/blob/fdbc8e7f0d7c4334ab82d5eb5e197c67c934a4e8/.taskcat.yml#L131-L136, where it uses the default of `Disabled`, have been succeeding for a while.
