### ISSUE TITLE
aws-node-daemonset-IRSA.template.yaml fails with RBACRole - CREATE_FAILED and ServiceAccount - CREATE_FAILED

### ISSUE THREAD

**Issue by nmquan2504** [aws-quickstart/quickstart-amazon-eks#401]
Dear all,

The new VPC deployment with default parameters fails at `aws-node-daemonset-IRSA.template.yaml` with this error:

![image](https://user-images.githubusercontent.com/16714353/158338322-fff8f35f-a2a7-48f9-ae6d-75ff984f4004.png)

Are there any ideas?

Thanks.

**Comment by moophlo** [comment]
Same issue here, tried everything, no luck

**Comment by moophlo** [comment]
![image](https://user-images.githubusercontent.com/902382/159444941-19efaa7a-b9b0-40a5-b6eb-ee8fc984c6c0.png)
To fix this rollback from last commit aws-node-daemonset-IRSA.template.yaml and upgrade bitnami image to: bitnami/kubectl:1.22

**Comment by jeevan-exa** [comment]
I am also facing the issue with `aws-node-daemonset-IRSA.template.yaml`, RBAC and ServiceAccount failed to create. But I am getting the following error.

```
Resource handler returned message: "__init__() got an unexpected keyword argument 'snapshotRequested' (TypeError)" (RequestToken: a2bce77f-e173-25cf-2051-4f2a7222430b, HandlerErrorCode: InvalidRequest)
```

Any idea on how to resolve it? I am using latest aws-quickstart only.

**Comment by tlindsay42** [comment]
Sorry for the delay. This should've been resolved a while back in https://github.com/aws-quickstart/quickstart-amazon-eks/pull/453 + https://github.com/aws-quickstart/quickstart-kubernetes-resource-provider/pull/34. Please re-open if still an issue, and if urgent/impacting business, please open a ticket with AWS Support.
