### ISSUE TITLE
BastionAutoScalingGroup create failed

### ISSUE THREAD

**Issue by ruiyaoOps** [aws-quickstart/quickstart-amazon-eks#411]
we failed to create an EKS cluster through [amazon-eks-entrypoint-new-vpc](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-entrypoint-new-vpc.template.yaml) in CloudFormation of AWS.
After investigation, we found that it was because the security group created by EKS quickstart has no inbound rules, it should allow access to 0.0.0.0/0.

The inbound rules of security groups created in older versions:
![image](https://user-images.githubusercontent.com/35256376/161937338-3030d87e-4545-4895-9658-5331befef8ee.png)

I think the cause of this problem is that the security group created in QS has no inbound rules, it should allow access to 0.0.0.0/0

**Comment by ruiyaoOps** [comment]
Here's why it fails without inbound  rules
https://github.com/aws-quickstart/quickstart-amazon-eks/issues/9
@troy-ameigh

**Comment by troy-ameigh** [comment]
I am looking into this.

**Comment by struhtanov** [comment]
I've found out that the reason of failure in my case was in this line:
`chown -R ssm-user:ssm-user /home/ssm-user/.kube/`
ssm-user is missing in aws ec2 instance.

I've commented that line in bastion_bootstrap.sh and was able to successfully setup a cluster.

Not an expert here, just telling which steps helped.

**Comment by troy-ameigh** [comment]
This has been resolved and should be uploaded to s3
