### ISSUE TITLE
AwsNodeIrsa-RIECFYI76E0A/d18bcc30-bb15-11ec-aafd-0aaa6607c179 was not successfully created.

### ISSUE THREAD

**Issue by competiscanv2** [aws-quickstart/quickstart-amazon-eks#414]
Hello,

when creating an EKS cluster from a cloud formation template EKS  cluster is created but after some time shows an error for AwsNodeIrsa.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/62908325/163170485-db76a490-3d46-4069-8728-424316aed049.png)

Embedded stack arn:aws:cloudformation:us-west-2:078398740737:stack/Competiscanv2Product-search-EKS-9-EKSStack-116P5SMQG9UNB-AwsNodeIrsa-RIECFYI76E0A/d18bcc30-bb15-11ec-aafd-0aaa6607c179 was not successfully created: The following resource(s) failed to create: [RBACRole, ServiceAccount].

Embedded stack arn:aws:cloudformation:us-west-2:078398740737:stack/Competiscanv2Emails-search-EKS-10-EKSStack-1IUCL0JRX1R99/156838c0-bb12-11ec-972e-0662eefc410f was not successfully created: The following resource(s) failed to create: [AwsNodeIrsa].

**Comment by tylercd100** [comment]
Hello! I was running in to this issue as well but managed to resolve it by deleting all of the EKS quickstart cloud formation stacks. Once they were completely removed I was then able to deploy the stack successfully. Hope this helps someone.
