### ISSUE TITLE
Can't deploy EKS cluster

### ISSUE THREAD

**Issue by akorolyov** [aws-quickstart/quickstart-amazon-eks#416]
region: us-east-1
URL with params https://us-east-2.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/quickcreate?
templateUrl=https%3A%2F%2Faws-quickstart.s3.us-east-1.amazonaws.com%2Fquickstart-amazon-eks%2Ftemplates%2Famazon-eks-entrypoint-new-vpc.template.yaml&
stackName=test-eks&
param_RancherIntegration=Enabled&
param_RemoteAccessCIDR=0.0.0.0/24&
param_KeyPairName=dev-eks&
param_PerAccountSharedResources=No&
param_PerRegionSharedResources=No&
param_ProvisionBastionHost=Disabled&
param_EKSClusterName=test-dev&
param_EKSPublicAccessEndpoint=Enabled&
param_AdditionalEKSAdminUserArn=arn:aws:iam::208315649567:group/local-admin&
param_AdditionalEKSAdminRoleArn=arn:aws:iam::208315649567:role/eksClusterRole&
param_VPCCIDR=10.22.0.0/16&
param_PrivateSubnet1CIDR=10.22.0.0/19&
param_PrivateSubnet2CIDR=10.22.32.0/19&
param_PrivateSubnet3CIDR=10.22.64.0/19&
param_PublicSubnet1CIDR=10.22.128.0/20&
param_PublicSubnet2CIDR=10.22.144.0/20&
param_PublicSubnet3CIDR=10.22.160.0/20&
param_AvailabilityZones=us-east-1a,us-east-1b,us-east-1c

Request

{'RequestType': 'Create', 'ServiceToken': 'arn:aws:lambda:us-east-1:208315649567:function:test-eks-EKSStack-MU1KNTUXDJ-LambdaSSMExecute-wg1ZBHje4LRI', 'ResponseURL': 'https://cloudformation-custom-resource-response-useast1.s3.amazonaws.com/arn%3Aaws%3Acloudformation%3Aus-east-1%3A208315649567%3Astack/test-eks-EKSStack-MU1KNTUXDJSB-RancherStack-NGUKHYFFW0Z2/b04f1290-cc43-11ec-b37c-12505c86b407%7CExecuteSSMAutomation%7Cd5257337-7bae-4c7b-80f0-5b5ef6108fc4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220505T072022Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Credential=%2F20220505%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=', 'StackId': 'arn:aws:cloudformation:us-east-1:208315649567:stack/test-eks-EKSStack-MU1KNTUXDJSB-RancherStack-NGUKHYFFW0Z2/b04f1290-cc43-11ec-b37c-12505c86b407', 'RequestId': 'd5257337-7bae-4c7b-80f0-5b5ef6108fc4', 'LogicalResourceId': 'ExecuteSSMAutomation', 'ResourceType': 'Custom::ExecuteSSMAutomation', 'ResourceProperties': {'ServiceToken': 'arn:aws:lambda:us-east-1:208315649567:function:test-eks-EKSStack-MU1KNTUXDJ-LambdaSSMExecute-wg1ZBHje4LRI', 'AutomationAssumeRole': 'arn:aws:iam::208315649567:role/test-eks-EKSStack-MU1KNTUXD-SSMAutomationRole-3TNQ9CY2AHF8', 'QSS3BucketName': 'aws-quickstart', 'DomainName': 'aws.private', 'EKSClusterName': 'test-dev', 'AWSRegion': 'us-east-1', 'QSS3KeyPrefix': 'quickstart-amazon-eks/submodules/quickstart-eks-rancher/', 'PrivateSubnet1ID': 'subnet-0e5e1772ba40531ba', 'SecurityGroup': 'sg-072159beb0f74ecbf', 'QSS3BucketRegion': 'us-east-1', 'StackName': 'test-eks-EKSStack-MU1KNTUXDJSB-RancherStack-NGUKHYFFW0Z2', 'IAMRole': '', 'DocumentName': 'tests-eks-EKSStack-MU1KNTUXDJSB-RancherStack-NGUKHYFFW0Z2-RancherInstallerSetup-t20rMvYIoE38'}}

Error:
{'Error': 'Parameter validation failed:\nInvalid length for parameter Parameters.IAMRole[0], value: 0, valid min length: 1'}

**Comment by tlindsay42** [comment]
@akorolyov Sorry for the delay. This was caused by the configuration of `param_RancherIntegration=Enabled` + `param_ProvisionBastionHost=Disabled` along with [no existing bastion role specified in an advanced EKS config stack](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-advanced-configuration.template.yaml#L222). 

As indicated by the specified error, the Rancher integration requires an existing IAM Role that's a member of the `system:masters` group in the EKS config map as an input parameter value ([reference](https://github.com/aws-quickstart/quickstart-eks-rancher/blob/9ca20558a2e48ca919a96170599dce114eca4084/templates/rancher.template.yaml#L88-L90)).
