### ISSUE TITLE
Lambda create_stack fails when using reserved 'aws:' tags

### ISSUE THREAD

**Issue by jonjozwiak** [aws-quickstart/quickstart-amazon-eks#42]
When launching this template from AWS Service Catalog, the CfnStackAssumeRole lambda function (QuickStartStackMakerLambda) fails due to using reserved tags.  The error message the Lambda returns is as follows: 

An error occurred (ValidationError) when calling the CreateStack operation: aws: prefixed tag key names are not allowed for external use.
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 133, in cfn_handler
physical_resource_id, response_data = create_func(event, context)
File "/var/task/lambda_function.py", line 331, in create
}] + parent_properties['Tags']
File "/var/runtime/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 612, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: aws: prefixed tag key names are not allowed for external use.

**Comment by jaymccon** [comment]
fixed in b057fa5a242bcabfab44bc6bc4b31b36fb74a8da
