### ISSUE TITLE
Update of the EKS stack fails with "the following resource(s) failed to update: [JobResource]."

### ISSUE THREAD

**Issue by denitsa-sabeva** [aws-quickstart/quickstart-amazon-eks#438]
I'm trying to update an already created EKS stack based on this template, however the update of AwsNodeIrsa fails with the following message: resource is failing with “Currently in UPDATE_FAILED with reason: The following resource(s) failed to update: [JobResource].”. Is there something that can be done for a successfull update?

**Comment by tlindsay42** [comment]
Hi @denitsa-sabeva, sorry for the delay. This should've been resolved a while back in https://github.com/aws-quickstart/quickstart-amazon-eks/pull/453 + https://github.com/aws-quickstart/quickstart-kubernetes-resource-provider/pull/34. Please re-open if still an issue, and if urgent/impacting business, please open a ticket with AWS Support.
