### ISSUE TITLE
Newly created bastion instance doesn't have kubeconfig

### ISSUE THREAD

**Issue by saravanan30erd** [aws-quickstart/quickstart-amazon-eks#44]
To test bastion autoscaling, I removed the running bastion server which created by cloud-formation initially. New bastion server is created as expected, it doesn't have kubeconfig file. However I tried to create kubeconfig file using `update-kubeconfig` but its not working and provides `error: the server doesn't have a resource type "svc"`

Refer: https://docs.aws.amazon.com/eks/latest/userguide/getting-started-console.html
`When an Amazon EKS cluster is created, the IAM entity (user or role) that creates the cluster is added to the Kubernetes RBAC authorization table as the administrator (with system:master permissions. Initially, only that IAM user can make calls to the Kubernetes API server using kubectl.` 

So I am trying to use the same user which used to create the cloud-formation.

**Comment by nfairoza** [comment]
I noticed same problem. I think it is because the AlternativeInitializationScript is given as AWS::CloudFormation::Init metadata when creating launch configuration, instead of adding it as UserData in /quickstart-amazon-eks/submodules/quickstart-linux-bastion/templates/linux-bastion.template @vsnyc

**Comment by vsnyc** [comment]
This has been fixed in commit: https://github.com/aws-quickstart/quickstart-amazon-eks/commit/29a1d8da363c8ffd8f3b7f1f8725d85d04657a3b
