### ISSUE TITLE
Cannot deploy the EKS using quickstart-amazon-eks with new vpc [!Important]

### ISSUE THREAD

**Issue by jeevan-exa** [aws-quickstart/quickstart-amazon-eks#447]
Using the following Cloud Formation template,
[amazon-eks-entrypoint-new-vpc.template.yaml](https://aws-quickstart.s3.amazonaws.com/quickstart-amazon-eks/templates/amazon-eks-entrypoint-new-vpc.template.yaml)

Used all default values provided.

## Error
Cloud Formation fails at `AwsNodeIrsa` while creating the RBACRole and ServiceAccount. I have tried several times in different regions but ended up with the same error. Attached are the error message and screenshot.

`Resource handler returned message: "__init__() got an unexpected keyword argument 'snapshotRequested' (TypeError)" (RequestToken: 049e7fc1-dfc8-da59-613d-26c3e14d8da9, HandlerErrorCode: InvalidRequest)`

![image](https://user-images.githubusercontent.com/63390384/189543470-37b67fae-948e-4194-b7ea-c241cf250509.png)

Any fix or tips to fix would be really appreciated!

**Comment by tlindsay42** [comment]
Hi @jeevan-exa! Sorry for the delay. This should be resolved in https://github.com/aws-quickstart/quickstart-kubernetes-resource-provider/pull/34 + https://github.com/aws-quickstart/quickstart-amazon-eks/pull/453. Please reopen if still an issue and open a case with AWS Support if urgent.
