### ISSUE TITLE
Advanced Configuration companion template is only allows up to Kubernetes v1.22 to be specified

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-amazon-eks#456]
Can the following please be done:
- allowed values be updated to the actual latest supported by the EKS QuickStart
- update release instructions for the EKS QuickStart to note that when the main template is validated for a new Kubernetes version, that the Advanced Configuration Template needs to be updated to allow that new version to be specified.

I can create a PR if I know the newest supported version and what document (or code comment) would help avoid trailing updates in the future.

cc: @troy-ameigh

**Comment by tlindsay42** [comment]
@DarwinJS: I updated this correctly to include `v1.23` as part of [#443](https://github.com/aws-quickstart/quickstart-amazon-eks/pull/443/files#diff-5b17cf53bb585fedb1b1893311f47f46a8334b6685a28622f7512c2c24253cc8R214), and it's still set correctly in main ([reference](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/340b53e71586a8b2c4197fd10e96d9ce541c6a59/templates/amazon-eks-advanced-configuration.template.yaml#L214). If this is still an issue, please re-open.
