### ISSUE TITLE
Value 'disabled-onlyssmaccess' for 'RemoteAccessCIDR' causes error

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-amazon-eks#457]
Code line: https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-entrypoint-new-vpc.template.yaml#L399

Error: 
![Screen Shot 2022-11-07 at 12 33 28 PM](https://user-images.githubusercontent.com/11597190/200376680-0f69f0ca-044f-4f3e-b425-b8448e3f37fd.png)

Originally this was intended to be used along with a blank value for 'KeyPairName' so that no keypair is required and no security group rule is added for a bastion ingress so that only SSM Connections area allowed.

**Comment by netapp-dhruv-tyagi** [comment]
Hi, I'm facing the same issue. I've tried the below combinations:

-----------------------
KeyPairName: mentioned
RemoteAccessCIDR: 0.0.0.0/0
-----------------------
KeyPairName: mentioned
RemoteAccessCIDR: disabled-onlyssmaccess
-----------------------
KeyPairName: empty
RemoteAccessCIDR: disabled-onlyssmaccess
-----------------------


Is there any scenario where the stack goes to completion without failing as a temporary workaround?

**Comment by DarwinJS** [comment]
It works when I use 198.51.100.0/24 - which is identified as a special IP address for documentation: https://www.rfc-editor.org/rfc/rfc5735

**Comment by tlindsay42** [comment]
Deployment of this change has been delayed due to https://github.com/aws-quickstart/quickstart-amazon-eks-cluster-resource-provider/issues/48. Reopening until the fix is deployed.
