### ISSUE TITLE
Update helm resource provider to at least helm 3.9

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-amazon-eks#463]
Update https://github.com/aws-quickstart/quickstart-helm-resource-provider to take in this fix in helm 3.9 and later: https://github.com/helm/helm/commit/0361dc85689e3a6d802c444e2540c92cb5842bc9 to get rid of this error: `admission webhook "vingress.elbv2.k8s.aws" denied the request: invalid ingress class: [IngressClass.networking.k8s.io](http://ingressclass.networking.k8s.io/) "gitlab-nginx" not found` in the GitLab Quick Start.

Placing this issue in quickstart-amazon-eks because it will need to be updated to consume the updated helm resource provider.

**Comment by tlindsay42** [comment]
Working on this through https://github.com/aws-quickstart/quickstart-amazon-eks/issues/463
