### ISSUE TITLE
Still ask for Mulesoft license even when MuleSoft Anypoint Runtime Fabric integration is set 'Disabled' 

### ISSUE THREAD

**Issue by cheungwn** [aws-quickstart/quickstart-amazon-eks#479]
The stack ran into issue and rollback due to blank value on MuleLicenseKeyinbase64 while MuleSoft Anypoint Runtime Fabric integration is set to'Disabled'

**Comment by tlindsay42** [comment]
Unable to reproduce and can't identify a scenario where this happen. If this is still an issue, please provide additional troubleshooting info. If urgent, please open a ticket with AWS Support.
