### ISSUE TITLE
CloudFormation fail on GetCallerArn Lambda function

### ISSUE THREAD

**Issue by es1o** [aws-quickstart/quickstart-amazon-eks#48]
Hello.
I use cloud formation template `amazon-eks-master.template.yaml` to create my cluster.

I destroyed cluster before weekend and now I can't create EKS cluster because of error in CallerArn Resource.

CallerArn runs lambda function GetCallerArnLambda. I've checked CloudWatch logs and see a lot of logs that looks like: 
```
"message": "Event not in cloudtrail yet, 8 retries left"
```

After that I got error: 
```
"exception": "Traceback (most recent call last):\n  File \"/opt/python/crhelper/resource_helper.py\", line 190, in _wrap_function\n    self.PhysicalResourceId = func(self._event, self._context) if func else ''\n  File \"/var/task/lambda_function.py\", line 65, in create\n    return helper.Data['Arn'].split('/')[1]\nIndexError: list index out of range"
```
Line number 56 has been added 3 days ago probably after I destroyed my cluster because I live in CEST timezone. In Friday I was able to create cluster using that code.

Could you help me? This is a blocker for me and I'm beginner in EKS. Maybe I have something misconfigured but I don't know what.

**Comment by e100** [comment]
New to EKS also, having same problem and seeing same errors.

**Comment by jaymccon** [comment]
@es1o @e100 looks like the newly added feature to automatically add the creator of the stack as a kubenernetes user is unable to resolve the format of your iam identity. 

Logic has been added to skip adding the user if this occurs, the GetCallerArnLambda should now complete, but not add your user (so you'll need to use the bastion host for k8s api operations).

Additionally the `GetCallerArnLambda` will log the unhandled arn in these cases, it would be helpful if you could post the arn's from those logs so that we can add handling for it.

**Comment by e100** [comment]
We use AWS Organizations. My IAM user is in the parent account and I was running this stack under an assumed role in a child account.

It still does not work for me

` "message": "list index out of range"
  "exception": "Traceback (most recent call last):\n  File \"/opt/python/crhelper/resource_helper.py\", line 190, in _wrap_function\n    self.PhysicalResourceId = func(self._event, self._context) if func else ''\n  File \"/var/task/lambda_function.py\", line 68, in create\n    return helper.Data['Arn'].split('/')[1]\nIndexError: list index out of range"`

**Comment by jaymccon** [comment]
@e100 can you provide the log message from line 59, should contain `failed to parse calling arn ` and an arn in the message

**Comment by es1o** [comment]
@e100 @jaymccon I have te same situation, I also in organisation. My account is a child account in organisation, but I have administration access.

Today I'm going to test if work for main account and I'll provide some logs.

**Comment by e100** [comment]
I do not see any messages in the logs related to line 59.

**Comment by es1o** [comment]
@jaymccon Today I had different message, GetCallerArnLambda run and when retries count to 0 I've got that error:

```
    "message": "unexpected error",
    "exception": "Traceback (most recent call last):\n  File \"/var/task/lambda_function.py\", line 71, in create\n    return helper.Data['Arn'].split('/')[1]\nIndexError: list index out of range"
```

Cluster has been created and it is operative. Before, I had that error and retries didn't count to 0 because lambda function got something from cloudtrail Looks like something is different than 2 days ago.

**Comment by jaymccon** [comment]
I added a catch-all to essentially ignore, rather than fail on this function.to be clear this is a workaround, and will result in the iam entity you launch the stack with NOT being granted access to the kubernetes api, should you want to enable this you will need to follow the eks documentation on adding additional users, using the bastion host to update the configmap.

**Comment by jaymccon** [comment]
I've added some more logging, so hopefully future runs will log the unhandled arn so we can look at parsing it instead of just skipping. If you happen to do another eks stack launch, it would be very helpful to get the log line from line `55`, message will start with `arn from cloudtrail: `. Note: this logging change will only be live in s3 in roughly 2 hours from now.

**Comment by e100** [comment]
I just created a stack with success.
No logs with `arn from cloudtrail`


`"message": "Event not in cloudtrail yet, 0 retries left"`

`"exception": "Traceback (most recent call last):\n  File \"/var/task/lambda_function.py\", line 71, in create\n    return helper.Data['Arn'].split('/')[1]\nIndexError: list index out of range"`

**Comment by es1o** [comment]
@e100 I had the same situation.

**Comment by jaymccon** [comment]
apologies, the needed commit https://github.com/aws-quickstart/quickstart-amazon-eks/commit/87e1539fdaaec58e1cb01a3b1748c20bb47e6556 has not been promoted yet due to a glitch in our ci. I'll update once it's through.

**Comment by jaymccon** [comment]
@e100 @es1o change is now live, if you are able, please retry and post log event.

**Comment by es1o** [comment]
@jaymccon I tried again and I had

`"message": "Event not in cloudtrail yet, 0 retries left"`

Next:
```
"message": "enabling send_response"
"message": "_send_response: True"
"message": "CFN response URL: https://cloudformation-custom-resource-response-eucentral1.s3.eu-central-1.amazonaws.com/arn%3Aaws%3Acloudformation%3Aeu-central-1%3A340547479101%3Astack/esio-eks-EKSStack-1LG7Jdsa5-EKSControlPlane-22P1HGB8AFPdasCCallerArn%7Ca43a7dbc-92ac-4e33-8871-1fad44dec198?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20190617T074009Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7199&X-Amz-Credential=AKdsaad%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Signature=c916eeasdsad6356f0b"
"message": {
        "Status": "SUCCESS",
        "PhysicalResourceId": "NotFound",
        "StackId": "arn:aws:cloudformation:eu-central-1:dsa:stack/esio-eks-EKSStack-1LG7JFYU36585-EKSControlPlane-22P1Hdas300f3c01c",
        "RequestId": "a43a7dbc-92ac-4e33-8871-1fad44dec198",
        "LogicalResourceId": "CallerArn",
        "Reason": "",
        "Data": {
            "Arn": "NotFound"
        }
    }
"message": "CloudFormation returned status code: OK"
```

**Comment by jaymccon** [comment]
closing this for now, even though there are potentially some cases where the caller is not added to k8s, but at least it won't result in a failure. If anyone experiences this in the future, please open a new issue, providing cloudwatch logs for the `GetCallerArnLambda` and the CloudFormation CreateStack event (for the parent stack) from CloudTrail. Be sure to redact any personal info before posting in github,
