### ISSUE TITLE
Help text for parameters that need to be in both the advanced and regular template

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-amazon-eks#482]
When I don't specify a parameter in the advanced template, but DO specify it in the regular template, my prior experiences with systems that converge configuration variables is that a null in a higher level template would not override a specified value in a lower level one.

In the case of this CF stack, this is an error in my thinking, but I feel a predictable error that many others will make.

Since many parameters in the advanced template MUST have a default value because they have a valid list - they aren't passed as null, but as a specific value.

So help text should be craft for these to appear in the regular template that highlights this. Maybe something like:

"IF the advanced template is in use, this parameter value will always come from that template (including the default value from the advanced tempalte) and so this parameter must be specified in the advanced template whenever it is in use."

I also think the term "Advanced Template" is misleading as it sounds like a super-edition of the main one. It might help add clarity to refer to it as "Parameter Configuration Template" which "is predeployed and sets hidden parameters and parameter overrides for the stack."

**Comment by tlindsay42** [comment]
Thanks @DarwinJS!
