### ISSUE TITLE
Issue with the csi driver on new 1.23 EKS cluster

### ISSUE THREAD

**Issue by JonathanManass** [aws-quickstart/quickstart-amazon-eks#485]
Hi,

When trying to create a brand new EKS cluster in kubernetes version 1.23, I am not able to create any PVCs as it gives this message : "waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator".

Now I know there's a warning message on older clusters mentioning that we'd have to manually install the driver before updating to 1.23 but that it should work fine on a new 1.23 cluster.

This does not seem to be the case when deploying through this quickstart.

So if any one can tell me whether that is actually the issue here or it's something else entirely and has any ideas of how to fix this.
Thanks a lot for any help.

**Comment by troy-ameigh** [comment]
We are looking into this.

**Comment by FedericoYST** [comment]
Hi All,
Is there any update on this? 

Thanks in advance,
Federico,
