### ISSUE TITLE
Cloudformation failure updating HelmLambda

### ISSUE THREAD

**Issue by kkolk** [aws-quickstart/quickstart-amazon-eks#49]
Tried to update my existing stack with recent improvements that take care of adding the creator automatically and now I'm seeing this when the function stack is deploying:
```
Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. 
The actual size is 332476862 bytes. 
(Service: AWSLambdaInternal; Status Code: 400; 
Error Code: InvalidParameterValueException; 
Request ID: 3ac74460-9692-11e9-a5e3-f5c0730d16c7)
```
If you rename the cloudformation resource from say HelmLambda to HelmLambdaFunction to force a recreation and try again it works without issue.   But it looks like this function as setup can't be updated without triggering this.

(Not sure this is a Quickstart issue or a Lambda issue...)

**Comment by jaymccon** [comment]
This is due to the way CloudFormation does Lambda Function updates, and the size of the Helm deployment package, so there is not likely anything we can do on the QuickStart side. 

Thanks for providing a workaround though @kkolk

**Comment by jaymccon** [comment]
Since migrating to a CFN Registry type this should no longer apply.
