### ISSUE TITLE
Unable to pull images from AWS ECR registry

### ISSUE THREAD

**Issue by FedericoYST** [aws-quickstart/quickstart-amazon-eks#490]
**Problem**: 
Enabling _IAM Roles for Service Accounts (IRSA_) with the following CloudFormation template: [ aws-node-daemonset-IRSA.template.yaml](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/aws-node-daemonset-IRSA.template.yaml) the following managedPolicy is missing:

- arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

This cause an ImagePullBackOff during any image pull operation from any AWS ECR registry.

Even if the policy is present in the eks-quickstart-ManagedNodeInstance role created by the shared resources the worker node are not able to perform the pull operation.

**Resolution**:
Add the _**AmazonEC2ContainerRegistryReadOnly**_ policy in the [ aws-node-daemonset-IRSA.template.yaml](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/aws-node-daemonset-IRSA.template.yaml) when creating the _AWSNodeIAMRole_ Role.

**Comment by tlindsay42** [comment]
Thanks @FedericoYST, would you like to submit a pull request for this? Easy enough to implement with the provided detail if not. ?

**Comment by tlindsay42** [comment]
Circling back- I was not able to reproduce this and recalled that the [VMware Tanzu Application Platform on EKS project](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/) that consumes this project as a git submodule has some examples of the IRSA config for achieving this.

* https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/main/templates/aws-tap-entrypoint-existing-vpc.template.yaml#L741-L755
* https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/main/templates/aws-tap-entrypoint-existing-vpc.template.yaml#L1165-L1257

Closing for now. Please open a ticket with AWS Support if you experience further issues. If you want to re-open this issue, please provide additional troubleshooting info, but AWS Support is going to be the much faster route.

**Comment by tlindsay42** [comment]
After thinking about this one a bit more, I'm going to add the policy anyway as there's very little risk to granting it and will help cover a potential edge case.
