### ISSUE TITLE
Is this repo ready for EKS 1.24?

### ISSUE THREAD

**Issue by allquixotic** [aws-quickstart/quickstart-amazon-eks#493]
Quick question; I saw some commits related to EKS 1.24 like [this](https://github.com/aws-quickstart/quickstart-amazon-eks/commit/fab02335f5b93ccdb7cf5b6ca8601adf359fa966).

Are the templates in this repo fully upgraded to support EKS 1.24 (i.e., they will not error if we try to run them in a 1.24 environment) or is this still a work in progress as of now?

**Comment by tlindsay42** [comment]
👋  @allquixotic Yep, should be good to go. We run a battery of static analysis ([example](https://github.com/aws-quickstart/quickstart-amazon-eks/pull/492/checks)) & end-to-end tests before publishing changes to the production buckets (links in the documentation). All end-to-end test configs can be found in https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/.taskcat.yml. Open source projects like this are always works in progress though as components, dependencies, et cetera are changing all the time. If you experience any issues, please create a ticket with AWS Support first. GitHub issues are better for feature requests and questions, such as this. 😄

**Comment by tlindsay42** [comment]
If anything further is needed, please re-open with additional details.
