### ISSUE TITLE
Support for Container Insights for logs and metrics

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#58]
Stack creation option for Container Insights logs and metrics on EKS.

**Comment by macobo** [comment]
@tomiszili did this ever get resolved?

**Comment by tomiszili** [comment]
> @tomiszili did this ever get resolved?

nope, I changed my mind, i think the template is way too complicated now. But there is a quick install guide: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-EKS.html

**Comment by macobo** [comment]
Thanks for the context!
