### ISSUE TITLE
Support for custom kubectl command run with Lambda like as HelmLambda

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#59]
This would be a good feature, to deploy custom yml setups which are not in any Helm repo.
Setup like this: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html

**Comment by jaymccon** [comment]
this was implemented in 58bea4e96e1f1f08429b23b01699a7a8933a9474
