### ISSUE TITLE
EKS Quickstart with CloudBees Core failing

### ISSUE THREAD

**Issue by johns2te** [aws-quickstart/quickstart-amazon-eks#61]
I cannot get the EKS quickstart to work.  Here is the error I receive and then when I go to delete the stack that fails as well.
<img width="1405" alt="Screen Shot 2019-09-30 at 7 27 59 PM" src="https://user-images.githubusercontent.com/16123258/65923958-bdd74480-e3b8-11e9-9b93-1d89721ce552.png">

**Comment by johns2te** [comment]
I've tried this Quickstart multiple times without success.

**Comment by schottsfired** [comment]
Hi @johns2te, thanks for reporting this. The error message in your screenshot shows a regex pattern that contains `arn`, and we see that the `EKSStack` is being deployed.

Only the `AdditionalEKSAdminArns` parameter would have `arn` in its input pattern:
https://github.com/aws-quickstart/quickstart-cloudbees-core/blob/master/templates/cloudbees-core-existing-vpc.template.yaml#L836-L855

Are you using the `AdditionalEKSAdminArns` parameter, and was it entered in according to the regex pattern in the error message?

It looks like we should have an `AllowedPattern` for `AdditionalEKSAdminArns` in the following code locations (among others):
https://github.com/aws-quickstart/quickstart-cloudbees-core/blob/master/templates/cloudbees-core-master.template.yaml#L117-L120
https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks-master.template.yaml#L183-L186

Thanks

**Comment by jaymccon** [comment]
It has been more than 2 months since this issue has been updated. There have been significant changes since that time and it's likely that this issue is no longer valid. I will close it as stale. If the issue is in fact still valid against the latest master branch, then comment here and we will re-open this issue.
