### ISSUE TITLE
bastion_bootstrap.sh fails for SLES 15

### ISSUE THREAD

**Issue by juan-vargas** [aws-quickstart/quickstart-amazon-eks#63]
There are commands that are not correct for this version like:

if [[ "${release}" == "SLES" ]]; then
        zypper install --non-interactive bash-completion
        echo "0 0 * * * zypper patch --non-interactive" > ~/mycron

has to be:
if [[ "${release}" == "SLES" ]]; then
        zypper install -y bash-completion
        echo "0 0 * * * zypper patch -y" > ~/mycron

And there is a mistake in these lines your are using the group where has to be the user:
mkdir -p /home/${user_group}/.kube
cat > /home/${user_group}/.kube/config <<EOF
chown -R ${user_group} /home/${user_group}/.kube/
chown ${user_group} /var/log/tiller.log
su ${user_group} -c "/usr/local/bin/helm init --client-only"

Thanks.

**Comment by jaymccon** [comment]
cc @kevinayres

**Comment by jaymccon** [comment]
thanks for the contribution @juan-vargas are you able to provide some details on the symptoms of the failures that this pr addresses ?

**Comment by juan-vargas** [comment]
Dear jaymccon,

These errors makes the bastion_bootstrap.sh to fail, and then the cloud formation detects the failure with a CREATE_FAILED status and do the rollback the stack (unless you selected not to do it)

I got errors like this:

Received FAILURE signal with UniqueId i-00caff407847cacd8
Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
The following resource(s) failed to create: [BastionAutoScalingGroup]

It is important to mention that these errors are only affecting to SLES 15 OS.

I did not detect it in Amazon Linux AMI's. 

Kind regards,

Juan

**Comment by jaymccon** [comment]
That is interesting, we test against SLES in our ci for the [suse-cloud-application-platform quick start](https://github.com/aws-quickstart/quickstart-suse-cloud-application-platform/), and we are not picking up failures, are you able to share some logs by email ? (my email is visible in my github profile)

**Comment by jaymccon** [comment]
@juan-vargas just checked and I see we're using a different bootstrap script for the CAP Quick Start

**Comment by juan-vargas** [comment]
Dar jaymccon,

What do you mean that you are using a different bootstrap script? The script that I was using it was from the EKS QuickStart.

Kind regards,

Juan

**Comment by juan-vargas** [comment]
Sorry now I see you corrected the script.

Thanks!
