### ISSUE TITLE
Upgrade CopyZips from Python 2.7 to 3.x

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/quickstart-amazon-eks#65]
Python 2.7 is EOL in January 2020. We need to upgrade the CopyZips function prior to then.

**Comment by troy-ameigh** [comment]
I have updated the Python 2.7 references to Python 3.7. All were in the "amazon-eks-master-existing-cluster.template.yaml" file. 

VPCLambdaCleanupLambdaFunction-Line:85
DeleteBucketContentsLambda-Line:127
CopyZipsFunction-Line:137

Starting testing.

**Comment by troy-ameigh** [comment]
This has passed its tests closing issue.
