### ISSUE TITLE
AWS kubernetes to EKS Migration

### ISSUE THREAD

**Issue by syniack** [aws-quickstart/quickstart-amazon-eks#73]
Is there a way to generate template of EKS from running AWS kubernetes cluster. We want to shift from AWS self manage kubernetes cluster to Manage EKS cluster.

**Comment by jaymccon** [comment]
This is out of scope for the EKS Quick Start. I'd suggest raising a question like this on more general Kubernetes/EKS discussion forums. Perhaps the Kubernetes slack ?
