### ISSUE TITLE
Resolved:  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

### ISSUE THREAD

**Issue by vmazo** [aws-quickstart/quickstart-amazon-eks#9]
![screen shot 2019-02-26 at 6 27 11 pm](https://user-images.githubusercontent.com/17888551/53456475-370e5380-39f4-11e9-80ed-858ed72fc7c8.png)

![screen shot 2019-02-26 at 6 29 40 pm](https://user-images.githubusercontent.com/17888551/53456670-d6334b00-39f4-11e9-9cf2-060b4f3e910a.png)

Can anyone help I'm unable to use cloudformation to successfully deploy this template. Create in Progress stays like this until it finally errors out.

vitalemazo@gmail.com thank you in advance !!

**Comment by jaymccon** [comment]
@vmazo can you please provide the errors from the `Events` tab of each stack that fails.

**Comment by vmazo** [comment]
Sure thank you so Much here you go 

![screen shot 2019-02-26 at 6 59 22 pm](https://user-images.githubusercontent.com/17888551/53457622-ba31a880-39f8-11e9-9ef0-bc085f21d018.png)

**Comment by vmazo** [comment]
I can SSH to the Bastion Host but it has no Kubectl installed

**Comment by vmazo** [comment]
I resolved the issue. The yaml is perfect. 

Users must remember 

1) Setup your route tables to communicated the internal subnets via nat , firewall , gateways

2) Setup your external Subnets to communicate outwards via a 0.0.0.0/0 route thru the aws IGW or something alike like a firewall elb for example

**Comment by vmazo** [comment]
I resolved the issue. The yaml is perfect.

Users must remember

1. Setup your route tables to communicated the internal subnets via nat , firewall , gateways
2. Setup your external Subnets to communicate outwards via a 0.0.0.0/0 route thru the aws IGW or something alike like a firewall elb for example

Once the Bastion Host saw the proper route on the public route table the template finished in under 25 minutes as described!!

Great Job everyone !!!!

**Comment by jaymccon** [comment]
This indicates that the bastion host failed to complete bootstrapping, unfortunately I can't tell much more without the logs from the instance. Of particular interest are:

`cat /var/log/messages | grep cloud-init`
`cat /var/log/cfn-*`

**Comment by vmazo** [comment]
Resolved please see Git response thank you !!!!!




Thank You


[signature_1985143643]

Where Investors Succeed
Vitale Mazo | Senior Systems Architect
521 5th Avenue, 29th Floor, New York, NY 10175
815 Brazos Street, Suite 1000 | Austin, TX 78701
Office: 212.292.4060 | Cell: 718.790.1150<mailto:718.790.1150>  Vmazo@novus.com<mailto:Vmazo@novus.com>

[cid:image014.png@01D4B34C.DF866400]<https://t.sidekickopen70.com/s1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJW7t6jvP7dSlJsN3M2drY1WLz4f1B1WwK03?t=https%3A%2F%2Fwww.novus.com%2F&si=7000000000913471&pi=0be91677-c58f-4d8b-aa85-bef3f23d7375>  [cid:image015.png@01D4B34C.DF866400] <https://t.sidekickopen70.com/s1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJW7t6jvP7dSlJsN3M2drY1WLz4f1B1WwK03?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fnovus-partners%2F&si=7000000000913471&pi=0be91677-c58f-4d8b-aa85-bef3f23d7375>   [cid:image016.png@01D4B34C.DF866400] <https://t.sidekickopen70.com/s1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJW7t6jvP7dSlJsN3M2drY1WLz4f1B1WwK03?t=https%3A%2F%2Ftwitter.com%2Fnovuspartners%3Flang%3Den&si=7000000000913471&pi=0be91677-c58f-4d8b-aa85-bef3f23d7375>

**Comment by jaymccon** [comment]
@vmazo Also worth noting that if you are using an existing VPC you must ensure that vpc and subnets are properly tagged as per the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html).

**Comment by vmazo** [comment]
Yup all good added resolution to GitHub thank you




Thank You


[signature_1985143643]

Where Investors Succeed
Vitale Mazo | Senior Systems Architect
521 5th Avenue, 29th Floor, New York, NY 10175
815 Brazos Street, Suite 1000 | Austin, TX 78701
Office: 212.292.4060 | Cell: 718.790.1150<mailto:718.790.1150>  Vmazo@novus.com<mailto:Vmazo@novus.com>

[cid:image014.png@01D4B34C.DF866400]<https://t.sidekickopen70.com/s1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJW7t6jvP7dSlJsN3M2drY1WLz4f1B1WwK03?t=https%3A%2F%2Fwww.novus.com%2F&si=7000000000913471&pi=0be91677-c58f-4d8b-aa85-bef3f23d7375>  [cid:image015.png@01D4B34C.DF866400] <https://t.sidekickopen70.com/s1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJW7t6jvP7dSlJsN3M2drY1WLz4f1B1WwK03?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fnovus-partners%2F&si=7000000000913471&pi=0be91677-c58f-4d8b-aa85-bef3f23d7375>   [cid:image016.png@01D4B34C.DF866400] <https://t.sidekickopen70.com/s1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJW7t6jvP7dSlJsN3M2drY1WLz4f1B1WwK03?t=https%3A%2F%2Ftwitter.com%2Fnovuspartners%3Flang%3Den&si=7000000000913471&pi=0be91677-c58f-4d8b-aa85-bef3f23d7375>

**Comment by schottsfired** [comment]
I hit this issue twice today while deploying [aws-quickstart/quickstart-cloudbees-core](https://github.com/aws-quickstart/quickstart-cloudbees-core) into a New VPC (via `taskcat`). Using @jaymccon 's suggestion I found the following in the logs:

```
+ cfn-init -v --stack tcat-tag-cloudbees-core-0250a26c-CloudBeesCoreExistingVPCStack-1XGR1V44OR-BastionStack-7BUEH935WUGO --resource BastionLaunchConfiguration --region us-east-1
Error occurred during build: Failed to retrieve https://taskcat-tag-quickstart-cloudbees-core-0250a26c.s3.amazonaws.com/quickstart-cloudbees-core/submodules/quickstart-amazon-eks/scripts/bastion_bootstrap.sh: HTTP Error 403 : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>DE1E1E70591E6B99</RequestId><HostId>lBPig01527BVNJ2PAcuV0QI8CAY4+OxQEmPsVeib+lezA5DSKPhx8yhssPO0votlFns1ObdjVxE=</HostId></Error>
+ cfn-signal -e 1 --stack tcat-tag-cloudbees-core-0250a26c-CloudBeesCoreExistingVPCStack-1XGR1V44OR-BastionStack-7BUEH935WUGO --resource BastionAutoScalingGroup --region us-east-1
```

Full log [here](https://gist.github.com/schottsfired/dccf69595704ed31b0a02c0769bdafe9).

Any ideas on the 403 error? The file is present in S3.

**Comment by schottsfired** [comment]
Update: I was able to get around the issue by using the `--enable-sig-v2` option with `taskcat`.
