### ISSUE TITLE
Bastion ec2-user doesn't have kubectl

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#94]
After start an SSM session to the bastion node, the ec2-user doesn't have kubectl installed.
```
[ec2-user@ip-10-0-138-39 ~]$ kubectl
bash: kubectl: command not found
```

**Comment by jaymccon** [comment]
It has been more than 2 months since this issue has been updated. There have been significant changes since that time and it's likely that this issue is no longer valid. I will close it as stale. If the issue is in fact still valid against the latest master branch, then comment here and we will re-open this issue.

**Comment by tomiszili** [comment]
Hi @jaymccon!

This problem is still exists on the bastion host, both the kubectl and the aws-iam-authenticator are not installed for the "ec2-user" user, only the root has these programs.

**Comment by troy-ameigh** [comment]
I have reopned the issue however they are working from ec2-user for me. See attached screen shot. 
![Screen Shot 2020-05-28 at 11 21 48 AM](https://user-images.githubusercontent.com/55170274/83167377-cca40180-a0d5-11ea-9be4-c36772548665.png)

**Comment by tomiszili** [comment]
@troy-ameigh 
Did you use the bootstrap script from the master or from the develop branch?

**Comment by troy-ameigh** [comment]
From master

**Comment by tomiszili** [comment]
inserting these lines after https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/scripts/bastion_bootstrap.sh#L467
solved this problem
```
    echo 'export PATH=/usr/local/bin:$PATH' >> /home/${user}/.bashrc
    source /home/${user}/.bashrc
```

**Comment by troy-ameigh** [comment]
We will look into this, however, I just did another pull from master and it is working fine without this. Are you using the lastest version?

**Comment by tomiszili** [comment]
> We will look into this, however, I just did another pull from master and it is working fine without this. Are you using the lastest version?

yes
