### ISSUE TITLE
Not possible to edit K8s labels with Managed Node Groups

### ISSUE THREAD

**Issue by schottsfired** [aws-quickstart/quickstart-amazon-eks#95]
Hiya! Thanks for adding Managed Node Groups. Very cool feature.

We enabled it for testing here: https://github.com/cloudbees/quickstart-cloudbees-core/blob/managed-node-groups/templates/cloudbees-core-existing-vpc.template.yaml#L877

And note that we are also applying K8s labels to the nodes, here: https://github.com/cloudbees/quickstart-cloudbees-core/blob/managed-node-groups/templates/cloudbees-core-existing-vpc.template.yaml#L873

However the labels applied via `BootstrapArguments` don't stick:
```
[ec2-user@ip-10-0-153-112 ~]$ kubectl get nodes -o custom-columns=NAME:.metadata.name,PARTITION:.metadata.labels.partition --sort-by=.metadata.labels.partition
NAME                          PARTITION
ip-10-0-95-72.ec2.internal    <none>
ip-10-0-66-12.ec2.internal    <none>
ip-10-0-19-131.ec2.internal   <none>
ip-10-0-29-208.ec2.internal   spot-agents
```
(the "spot agents" partition doesn't have the managed node groups feature enabled, hence why it has a `partition` label above)

In addition, the labels which are added to the default node pool (from: https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks-nodegroup.template.yaml#L969-L972) came out the other end looking like this:
```
Labels:             Key=Name
                    PropagateAtLaunch=true
                    Value=EKS-M0FQF4sVqnn4-cloudbees-core-regular-agents-Node
```

Our architecture relies on using K8s labels, and this looks like a blocker for us being able to add support for Managed Node Groups.

**Comment by troy-ameigh** [comment]
Looking into this
