### ISSUE TITLE
support spot instances for node groups

### ISSUE THREAD

**Issue by jaymccon** [aws-quickstart/quickstart-amazon-eks#97]
Allow nodegroups to be made up of spot instances. Template can be based off the excellent work here: https://github.com/aws-quickstart/quickstart-cloudbees-core/blob/master/templates/cloudbees-core-spot-nodes.template.yaml

**Comment by yanivpaz** [comment]
Is there plan to merge the spot template to master ?

**Comment by jaymccon** [comment]
implemented in #162
