### ISSUE TITLE
CopyZip function bucket error

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-amazon-eks#99]
Hi all,

I copied to my account S3 bucket the whole github repository, the S3 bucket has the default creation parameters.
When I want to deploy the cloudformation stack with the new QSS3Bucket, QSS3Key and the LAmbdaZipBucket left empty but the stack fails on the CopyZips function part with botocore copy error.
What S3 bucket configuration needed to enable this lambda to copy objects?

Thanks

**Comment by clayvan** [comment]
@tomiszili  I'm running into the same issue now. What did you do to fix it?

**Comment by tomiszili** [comment]
A solution for me was that I created the bucket (e.g.: cf-templates) and a folder (e.g.: eks) with the AWS management console, than I uploaded the repository content (quickstart-amazon-eks/*) into that folder. It was working properly for me.

My not working version was: i uploaded the quickstart-amazon-eks folder (as the git clone command downloads a repository) into the bucket (e.g.: cf-templates) root.

I think this is some S3 browser drag and drop upload issue.

**Comment by clayvan** [comment]
@tomiszili thanks for the quick response!

Well that is reaaally weird. Any chance I could convince you to share how you got all the files `quickstart-amazon-eks/*` into your S3 bucket without dragging and dropping the folder in your file browser?

I've tried via the CLI through these two methods with the same outcome (copyzips error)
```
aws s3 sync /path/to/quickstart-amazon-eks s3://mybucket/quickstart-amazon-eks/
aws s3 cp /path/to/quickstart-amazon-eks s3://mybucket/quickstart-amazon-eks --recursive
```

**Comment by schottsfired** [comment]
Lambda .zip packages are no longer present in `/functions/packages/` in the latest version of the EKS Quick Start. If you deploy your templates without Lambda .zip packages, you'll hit the CopyZips error.

The latest version of `taskcat` (v9) packages Lambda functions (into .zip files) for you, but note that it requires access to a `docker` daemon to do that. Once `taskcat` builds all the Lambda packages, it will upload them to S3 along with your templates, and you shouldn't hit the CopyZips issue.

Hope this helps!

**Comment by clayvan** [comment]
Now that makes more sense!

Wow not only did that work, but I never knew taskcat existed. Definitely a gamechanger. Thanks!

**Comment by ieyei** [comment]
> Lambda .zip packages are no longer present in `/functions/packages/` in the latest version of the EKS Quick Start. If you deploy your templates without Lambda .zip packages, you'll hit the CopyZips error.
> 
> The latest version of `taskcat` (v9) packages Lambda functions (into .zip files) for you, but note that it requires access to a `docker` daemon to do that. Once `taskcat` builds all the Lambda packages, it will upload them to S3 along with your templates, and you shouldn't hit the CopyZips issue.
> 
> Hope this helps!

I have the same issue. And I don't know what I should do to solve this problem.  Can you explain in more detail?

**Comment by techcto** [comment]
> I have the same issue. And I don't know what I should do to solve this problem. Can you explain in more detail?

One you get your taskcat project setup, run `taskcat test run --lint-disable`  and it will build your zips.
